### ISSUE TITLE
Issue with sendInitialEvent in WorkspaceFoldersFeature 

### ISSUE THREAD

**Issue by nfdiop** [microsoft/vscode-languageserver-node#1002]
Hi,

There seems to be an issue with this method https://github.com/microsoft/vscode-languageserver-node/blob/536cc154323d4d5d66c225a9ad5c5f259057f6f9/client/src/common/workspaceFolder.ts#L105.

The issue is that initially `currentWorkspaceFolders` and `this._initialFolders` are the same since they are initialised to the same value (ie: `workspace.workspaceFolders`). As a result, the arrays `added` and `removed` contain the same items.

We could change `arrayDiff` to do a deepComparison of arrays or change the initial values.

Happy to contribute.

Thanks

**Comment by dbaeumer** [comment]
The initial set of workspace folders is signaled in the intialize request. Since the communication to the server is async it can happen that between the sending of the request and the result processing new folders came in. The `sendInitialEvent` tries to compensate for this. It is not meant to send the initial set of folders.

I will close the issue. Please ping if you still see a problem with this.
