### ISSUE TITLE
Document diagnostics report not used when text document closed

### ISSUE THREAD

**Issue by JohnnyMorganz** [microsoft/vscode-languageserver-node#1013]
Using language client `8.0.2-next.5`. The server supports pull document diagnostics, but not workspace diagnostics.

The client (correctly) sends `textDocument/diagnostic` to pull a new report when a file is closed (i.e., is no longer managed).
However, the returned report by the server is not then used by the client - the old diagnostics still remain.

In my case, I want to clear the diagnostics of some files when they are closed / no longer managed, but this does not happen.

Minimal example: https://github.com/JohnnyMorganz/pull-diagnostics-bug

**Comment by dbaeumer** [comment]
@JohnnyMorganz thanks for the GitHub repository. I was able to reproduce this, however we need to think a little what the expected behavior would be in such a case. I opt to do the following:

- if the server supports workspace diagnostics then leave the diagnostics as is. The one from the workspace diagnostics will then catchup with any changes.
- if the server doesn't support workspace diagnostics we should not pull again for the document. Major reason is that pull doesn't pull for other closed documents. The client should instead simply clear the diagnostics for the document to bring it into the same state as if the document never got opened.

@aeschli since you are using pull now as well any ideas / advice here?

**Comment by dbaeumer** [comment]
I would basically implement the clear on the client side. Does that make sense to you @aeschli

**Comment by JohnnyMorganz** [comment]
Understandable that the client should be controlling when it shows diagnostics.
I guess my main ask would be is there any way of controlling this as a user, not necessarily as a server?

I feel like its quite important, as a user, that some diagnostics should be made available even when the file is closed (https://github.com/microsoft/vscode/issues/13953 shows the importance of this for js/ts), whilst other files can be ignored.
It seems that this is something wanted by other servers too (https://github.com/microsoft/vscode-languageserver-node/issues/848#issuecomment-652858418), where there are cases for errors to only be shown whilst a file is open for *some* (not necessarily all) files

Maybe this is out of scope for this repository/issue though. Its probably also possible to control this once we implement workspace diagnostics, unless that is also not really recommended there.

**Comment by aeschli** [comment]
@JohnnyMorganz You should looking into using workspace diagnostics
- Workspace diagnostics are shown for all resources, unless the ones open in an editor
- Document diagnostics are shown for the resources in open editors.
Your workspace diagnostics would not contain diagnostics for ignored resources, but the your document diagnostics would.
