### ISSUE TITLE
Can't get language-specific VS Code settings via workspace/configuration request

### ISSUE THREAD

**Issue by debonte** [microsoft/vscode-languageserver-node#1056]
Pylance is planning to enable the `editor.formatOnType` VS Code setting just for Python. There's docs on language-specific settings [here](https://code.visualstudio.com/docs/getstarted/settings%5C#_language-specific-editor-settings). In `settings.json` it looks like this:

```json
"[python]": {
    "editor.formatOnType": true
}
```

When sending a workspace/configuration request with `section` set to `editor` I seem to always get the global value of `editor.formatOnType`. Is there a way for me to get the python-specific value? I tried setting section to `[python].editor` and `python.editor` but no luck.

**Comment by dbaeumer** [comment]
You have to provide a `scopeUri` in the configuration item (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#configurationItem)

Then on the client side when reading the settings you need to honor that scope by calling https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#configurationItem with the proper configuration scope.  I usually try to find a text document for the URI or if this is not possible use the uri and a default language (e.g. `python` in our case).

I will close the issue since I think all the pieces are there.

**Comment by debonte** [comment]
Ok, so it's up to each particular server and client to agree on how to encode the language in the scope uri?

**Comment by dbaeumer** [comment]
For VS Code yes since a language mode is only associated with a text document. VS Code can't associate a language with a URI. This is an old outstanding feature request.
