### ISSUE TITLE
Pull diagnostics not being requested for newly opened files

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-languageserver-node#1064]
`"vscode-languageserver": "8.0.2"`

I'm seeing pull diagnostics not being requested properly in the markdown language server. You can test this by:

- In VS Code
- Set `"markdown.experimental.validate.enabled": true`
- Open `vscode-docs` repo
- Open `codebasics.md`
- Reload the window to get the server into a fresh state
- Introduce an error in a link path in `codebasics.md` and confirm an error is reported (just make a link point to a file that doesn't exist)
- Now open  `config-linux.md` and introduce an error
- Notice that no errors are reported

---

To debug this, I added a log function that logs whenever `connection.languages.diagnostics.on` is called:

https://github.com/microsoft/vscode/blob/3a5a458643eab4a198af55cffa961e8baa406b7b/extensions/markdown-language-features/server/src/languageFeatures/diagnostics.ts#L69

Using this, I see it called correctly for files that are open when the window loads, but not for newly opened files. In this example, I started with `codebasics.md` open and then opened `config-linux.md`:

![Screen Shot 2022-08-25 at 3 53 39 PM](https://user-images.githubusercontent.com/12821956/186782567-d80df849-e988-4521-b84c-62f2ad0fe232.png)

Instead of requesting diagnostics for `config-linux.md` when I open it, I instead see a new request for diagnostics for `codebasics.md` (this second request goes away if I turn off `interFileDependencies`)

All other features in the second file seem to work, it's just that diagnostics are not being requested on it. Any ideas what is going on?

**Comment by mjbvz** [comment]
This sounds similar to #1008 however I still see the bug with the latest publisher build (8.0.2)

**Comment by dbaeumer** [comment]
I looked into this and after upgrading the extension to 8.0.2 (it was still using 8.0.1; I guess because of a yarn.lock) everything works for me as expected running out of source from the vscode extensions folder. Here is a screen cast

![cast](https://user-images.githubusercontent.com/1931590/186898526-97975bb5-a6d2-417e-890c-8157e586ded7.gif)

I did noticed something: on first open the file is validated twice. Once through the tab open and a second time by the document being open. However that shouldn't cause any problems expect performance. I will look into fixing this.

I also noticed that you enable pull onChange and onSave. I should have made these exclusive since it doesn't make sense to enable both. In your scenario I think it is enough to validate onChange. 

Do you have any additional steps on how to reproduce this since you said you are still seeing this on `8.0.2`

**Comment by mjbvz** [comment]
Ah yes, I updated the server to 8.0.2. but missed updating the client! Good find and sorry for the noise

I will also remove `onSave` as you suggest!

**Comment by dbaeumer** [comment]
No problem. Found some other bugs while looking into this :-)
