### ISSUE TITLE
Question: `anyOf` vs `oneOf`

### ISSUE THREAD

**Issue by black-desk** [microsoft/vscode-languageserver-node#1073]
As the json schema spec says:

> 6.7.2 anyOf
>
>   This keyword's value MUST be a non-empty array.  Each item of the
>   array MUST be a valid JSON Schema.
>
>   An instance validates successfully against this keyword if it
>   validates successfully against **at least one** schema defined by this
>   keyword's value.

[ref](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-6.7.2)

> 6.7.3 oneOf
>
>   This keyword's value MUST be a non-empty array.  Each item of the
>   array MUST be a valid JSON Schema.
>
>   An instance validates successfully against this keyword if it
>   validates successfully against **exactly one** schema defined by this
>   keyword's value.

[ref](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-6.7.3)

I think all of `anyOf` in `metaModel.schema.json` should be `oneOf`.

- https://github.com/microsoft/vscode-languageserver-node/blob/8de18faed635819dd2bc631d2c26ce4a18f7cf4a/protocol/metaModel.schema.json#L211-L238

- https://github.com/microsoft/vscode-languageserver-node/blob/8de18faed635819dd2bc631d2c26ce4a18f7cf4a/protocol/metaModel.schema.json#L356-L366

- https://github.com/microsoft/vscode-languageserver-node/blob/8de18faed635819dd2bc631d2c26ce4a18f7cf4a/protocol/metaModel.schema.json#L487-L497

- https://github.com/microsoft/vscode-languageserver-node/blob/8de18faed635819dd2bc631d2c26ce4a18f7cf4a/protocol/metaModel.schema.json#L667-L701

@dbaeumer

**Comment by dbaeumer** [comment]
Actually I use a tool to generate the schema from a TypeScript file. The tool is: `ts-json-schema-generator`. The source of these `anyOf` are TS or types (e.g. https://github.com/microsoft/vscode-languageserver-node/blob/8de18faed635819dd2bc631d2c26ce4a18f7cf4a/tools/src/metaModel.ts#L122)

From a TS perspective an or type is not `oneOf`. It could well be that something matches against n entries in a OR type. 

I do agree that in these specific example `oneOf` is the more precise definition. But since I use a generator I don't want to postprocess the file by hand. We could ask the generator owners to improve this or at least provide a command line argument to control this.

I will close the issue. Please ping if you disagree with the resolution.
