### ISSUE TITLE
Define ordering when multiple outlines are present

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-languageserver-node#1077]
Is it possible for our custom doc symbols to appear first so that they are higher up in the outline view and show up as the bread crumbs for a document? In the screenshot below, we want the Solution tree to appear first.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/179807/190452505-e0d56381-8eda-4b61-84d5-7f06615c907a.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/179807/190452559-7ed65c17-ec31-436f-be4d-d67f75322fd9.png">

**Comment by dbaeumer** [comment]
Not that I am aware of. Since this depends on the editor providing the client API I recommend to ask that question in the VS Code repository using VS Code API only. If there is a way we can look into adopting this in LSP if possible.

I will close the issue. Please ping if you think there is something that needs to be done in LSP.
