### ISSUE TITLE
metamodel: include message types

### ISSUE THREAD

**Issue by michaelpj** [microsoft/vscode-languageserver-node#1079]
`RequestMessage`, `ResponseMessage`, and `NotificationMessage` are in the spec but missing from the metamodel. It would be handy to have them for completeness (and every implementation will probably need corresponding types, so we might as well generate them!).

**Comment by dbaeumer** [comment]
Actually, this is on purpose. These types are defined by JSONRPC and a generation tool could rely on a library to provide them (e.g. even in LSP we have the protocol which depends on vscode-jsonrpc, which defines these types).

I will close the issue since I think that the meta model shouldn't define these.
