### ISSUE TITLE
How to incorporate GitHub authentication into a language server

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode-languageserver-node#1094]
I am following [this sample](https://github.com/microsoft/vscode-extension-samples/tree/main/github-authentication-sample) to obtain GitHub authentication. The sample is based on client-side code, so I'm wondering how I would provide the authenticated GitHub session to the language server code. Do I just have to import the client side code (e.g. the `Credentials` class in the sample) in the server code or is there a language server API for this available?

**Comment by dbaeumer** [comment]
You can't use VS Code API classes in the server since there is no implementation behind it.

What you can do is the following:

- either have a custom message to transfer the credentials to the server
- use the `initializationOptions` property on the intialize request to send them to the server. See https://github.com/microsoft/vscode-languageserver-node/blob/18fe890c0e4cb96b1fc4ab94afabeb391ff3a4a0/protocol/src/common/protocol.ts#L1353

Hope that clarifies things

**Comment by gee4vee** [comment]
Thank you @dbaeumer. Is there some sample code to show how to send a custom message?

**Comment by gee4vee** [comment]
@dbaeumer Also, I think I would need to keep track of the session on the server so that it can be accessed during my parsing when the document changes. Is there a way I can persist the session on the server until it is needed?

**Comment by dbaeumer** [comment]
Best is to look at the test case. They define lots of custom messages: An example is: https://github.com/microsoft/vscode-languageserver-node/blob/c1e8f03672b38812e4691e1baac67402325ed4db/jsonrpc/src/node/test/connection.test.ts#L57

**Comment by gee4vee** [comment]
@dbaeumer Thanks. Do you know of a way to track the session on the server to use during parsing for things like doc symbols and completions?

**Comment by dbaeumer** [comment]
Actually I don't.
