### ISSUE TITLE
Provide the "globalStorageUri" field

### ISSUE THREAD

**Issue by Tarrowren** [microsoft/vscode-languageserver-node#1100]
I need `globalStorageUri` value as the root path of the cache, and I use `connection.sendRequest` to get it, so I can only initialize it in `connection.onInitialized`

```ts
  connection.onInitialized(async () => {
    await fileCache.ready(connection);
  });


...
    async ready(connection) {
      const uri = await connection.sendRequest(
        VSCodeStorageRequest.GLOBAL_STORAGE_URI
      );
      const globalStorageUri = URI.parse(uri);

      const cacheLocation = join(globalStorageUri.fsPath, "file-cache");
      await mkdir(cacheLocation, { recursive: true });
    },
```
But  `connection.onCompletion` starts working before cache initialization was complete.
Is it possible to prevent other methods from working until `onInitialized` is done, or provide `globalStorageUri` so that it can initialize my cache utils in `connection.onInitialize`?

**Comment by r3m0t** [comment]
You can put an object as `LanguageClientOptions.initializationOptions`, it will be in the first argument to the `onInitialize` event.

https://github.com/microsoft/vscode-languageserver-node/blob/4ee380e66e9d4c0ac64bd84080f723e770c05b25/testbed/client/src/extension.ts#L34

https://github.com/microsoft/vscode-languageserver-node/blob/c53b35e114c9781c60c5a60981045baa677fa311/server/src/common/server.ts#L994

Better to do the `join()` on the client side instead of in the LSP :)
