### ISSUE TITLE
`ProgressParams.value` should include `WorkDoneProgress*` types. 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1114]
Currently the `ProgressParams.value` type is `LSPAny`. 
```
                {
                    "name": "value",
                    "type": {
                        "kind": "reference",
                        "name": "LSPAny"
                    },
                    "documentation": "The progress data."
                }
```
This should likely be defined as `or` type with `WorkDoneProgressBegin`, `WorkDoneProgressEnd`, `WorkDoneProgressReport` and `LSPAny`. This way de-serializers can test with building these types ( `WorkDoneProgressBegin`, `WorkDoneProgressEnd`, WorkDoneProgressReport` ) before falling back to `LSPAny`.

**Comment by dbaeumer** [comment]
Actually, I would like to not do this since it gives a false impression. Then the questions raise why we don't add `CompletionItem[]` and all the other value types that are in the spec as a valid progress param type. 

See https://github.com/microsoft/language-server-protocol/blob/43c272c655ea181c4dd2e96b0d28a1fb269452a3/_specifications/lsp/3.17/language/completion.md#L753 as an example.

The progress reporting infrastructure is used for two different things:

- work done progress (both client and server initiated)
- partial result progress for specific requests (e.g. completion item request for example)

IMO the check for these three types should happen in the code that created the token for the work done progress.

I will close the issue. Please ping if you disagree.
