### ISSUE TITLE
Support for vscode 1.0.3 taking too long to be released

### ISSUE THREAD

**Issue by zorgntrwaw** [Microsoft/vscode-languageserver-node#119]
Sorry if this sounds rude, but what I'm trying to say is that [`vscode`](https://github.com/Microsoft/vscode-extension-vscode) 1.0.0 was released in September and there's still no support for this major version on the language server package. I see you guys are working on version 3 on the master branch, but the [last commit was 21 days ago](https://github.com/Microsoft/vscode-languageserver-node/commit/3330487fde99572bf3d975db4a0fb3bf99494219).

**Comment by XVincentX** [comment]
I agree - I can't move my code to TS 2.0 due to this thing.

I am willing to help and commit my time. What's missing here in order to release the new version? How can I contribute? @dbaeumer

**Comment by egamma** [comment]
@XVincentX suggest to take a look at https://github.com/Microsoft/vscode-eslint, it shows how to move to TS 2.0. What you need to make this happen is to add thenable.d.ts, pls see https://github.com/Microsoft/vscode-eslint/blob/master/eslint-server/src/thenable.d.ts

**Comment by dbaeumer** [comment]
@zorgntrwaw I am not sure I understand this. The library does work with vscode 1.0.0

@zorgntrwaw the problem is that the TS 2.0 adoption is somehow breaking as you have found out yourselve. That is why we decided to bump the version number to 3.0.0. But you can use the workaround from eslint to already convert to TS 2.0.

We should have a pre version that can be used with TS 2.0 soon.

**Comment by XVincentX** [comment]
Thanks for the tip @egamma , I'll try it.

**Comment by XVincentX** [comment]
It works. I'm on 2.0 now!

**Comment by dbaeumer** [comment]
And there is a new 3.0.1-alpha version that is on 2.0 as well.

**Comment by dbaeumer** [comment]
3.0.x shipped lately and addresses the issue.
