### ISSUE TITLE
`setTrace` notification is not sent when trace level changes.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-languageserver-node#1200]
https://github.com/microsoft/vscode-languageserver-node/blob/2e5571450daa3ebc96c2ff771432d77efc42ad53/client/src/common/client.ts#L883-L892

Looking at the code there, it seems like we don't send the notification on trace level change. Is this supposed to be handled manually? 
Additionally, should changing log level on the `traceOutputChannel` should automatically send a setTrace notification?

**Comment by dbaeumer** [comment]
This is actually on purpose since all the message tracing happens on the client side (except some server side stuff that only happens on initialization). So the problem might arise from a bad name. This is not a general trace log level. It is to enable JSON-RPC communication tracing.

> Additionally, should changing log level on the traceOutputChannel should automatically send a setTrace notification?

I am not sure I understand this. LSP has not adapted the new LogLevelApi from VS Code yet mainly since it will be a breaking change for all LSP clients.

**Comment by karthiknadig** [comment]
I see, so the way to enable tracing messages between client-server is to use the `<server-id>.server.trace`? 

I got confused by the name as `setTrace` method on the client sounds like it will also send the `setTrace` notification.

**Comment by dbaeumer** [comment]
That is correct. I will close the issue. Please ping if something is still unclear.
