### ISSUE TITLE
LSP API for all servers to persist state

### ISSUE THREAD

**Issue by pattobrien** [microsoft/vscode-languageserver-node#1205]
After looking over LSIF documentation, I'm curious if the LSP project has considered implementing similar ways to persist server state across server instances?

There are two distinct use cases I'm currently working on achieving with the dart language server (and in particular, the plugin package that allows others to tap into the language server):
- allow language servers to persist state when switching contexts or closing workspaces, avoiding the need for a cold reboot on next opening
- allow other IDE tools to work with the dumped state (e.g. a git hook that doesnt allow publishing commits if there are any diagnostics found on the project)

In general, I think LSIF shows a lot of promising concepts, although the recent work + abandonment of LSIF from the Sourcegraph team seems to highlight the lack of industry support for that particular protocol. Incorporating such concepts into LSP directly would have some benefit, I believe.

These are just preliminary thoughts, but I'd be willing to help think through a spec here.

**Comment by dbaeumer** [comment]
We discussed such a use case and came to the conclusion to leave the format a language server to persist state to the server since it can choose a better format than LSIF.

LSIF is meant as an language independent index format where a server can pick a language specific storage format. 

I will close the issue. Please ping if something is unclear.
