### ISSUE TITLE
Arrow function erroneously uses the `arguments` object

### ISSUE THREAD

**Issue by FinnChen** [microsoft/vscode-languageserver-node#1247]
According to the ES6 specification, arrow functions do not bind their own arguments object, and instead inherit it from their parent scope. 

In the following code snippet,  I think the intent is to check the number of args of the `sendNotification` method. But the `arguments` object here represents the  args of function `createConnection`.

```js
export function createConnection<...>(
	connectionFactory: (logger: Logger) => ProtocolConnection, watchDog: WatchDog,
	factories?: Features<...>,
): _Connection<...> {

	...
	let protocolConnection: _Connection<PConsole, PTracer, PTelemetry, PClient, PWindow, PWorkspace, PLanguages, PNotebooks> & ConnectionState = {
		listen: (): void => connection.listen(),

                ...
		sendNotification: (type: string | MessageSignature, param?: any): Promise<void> => {
			const method = Is.string(type) ? type : type.method;
			if (arguments.length === 1) {
				return connection.sendNotification(method);
			} else {
				return connection.sendNotification(method, param);
			}
		},
       }
...
```

See https://github.com/microsoft/vscode-languageserver-node/blob/main/server/src/common/server.ts#L1491

**Comment by dbaeumer** [comment]
Good catch. The lucky thing is that this doesn't introduce any wrong behavior since it is only there to make the TS compiler happy :-). At the end everything binds to this function: https://insiders.vscode.dev/github/microsoft/vscode-languageserver-node/blob/dbaeumer/tiny-mastodon-yellow/jsonrpc/src/common/connection.ts#L1266

which uses vargs.

I will look to change the code to avoid misinterpretation.
