### ISSUE TITLE
accessing workspace configuration during initialize

### ISSUE THREAD

**Issue by moosq** [microsoft/vscode-languageserver-node#1265]
While handling the `initialize` request from the client I'd like to access the workspace settings from the vscode extension. Unfortunately I get an `Unhandled method  workspace/configuration` error reply on the `workspace/configuration` notification. I'd like to adjust certain server capabilities through settings from the workspace configuration and I'd like to do it in the static registration as some clients (e.g. vim) don't seem to support dynamic registration of capabilities. Is it possible to allow at least handling of `workspace/configuration` notifications during this `initialize` phase or could you suggest any other possibility to achieve the desired behaviour?

vscode-languageclient version 8.1.0
LSP 3.16

**Comment by dbaeumer** [comment]
I actually don't want to do this since it makes initialization on the client side harder. What you can do is to send initial options via a property. See https://insiders.vscode.dev/github/microsoft/vscode-languageserver-node/blob/main/protocol/src/common/protocol.ts#L1373

I will close the issue. Please ping if the suggestion doesn't help.
