### ISSUE TITLE
LanguageClient adds an extra `--stdio` argument when using `TransportKind.stdio`

### ISSUE THREAD

**Issue by nhedger** [microsoft/vscode-languageserver-node#1440]
Hey,

I'm developing an extension that uses `LanguageClient` to create an LSP session over `stdio`, and it looks like the library is passing an extra `--stdio` argument to the the command. Since the executable that runs the LSP server does not support the `--stdio` argument, the server crashes.

Here's an example:

```ts
new LanguageClient(
	"my_client",
	{
		command: "/path/to/executable",
		transport: TransportKind.stdio,
		args: ["lsp"],
	},
	{
		outputChannel: logger,
		documentSelector: this.generateDocumentSelector(),
		traceOutputChannel: window.createOutputChannel("My LSP"),
	},
);
```

The binary that runs the LSP server expects the command to be `/path/to/executable lsp`

But the library appends an additional `--stdio` argument: `/path/to/executable lsp --stdio`, and since it's not supported by the command, it fails.

This can be an issue when the developer that creates the LSP client does not also maintain the LSP server, because he might be unable to adapt it to match the currently required behaviour.

Could this be removed? If not, would it be possible to explain why this argument is necessary?

Happy to contribute the change.

**Comment by dbaeumer** [comment]
It is there because it is an implementation recommendation of the spec (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#implementationConsiderations). 

However you can always pass a function as the server options which gives you full control on how the server is launch, including all command line arguments. 

See 

```ts
(() => Promise<ChildProcess | StreamInfo | MessageTransports | ChildProcessInfo>)
```

here: https://insiders.vscode.dev/github/microsoft/vscode-languageserver-node/blob/dbaeumer/personal-pinniped-aqua/client/src/node/main.ts#L126
