### ISSUE TITLE
The order of Request(completion) and Notification(did_change) seems to changed

### ISSUE THREAD

**Issue by He1pa** [microsoft/vscode-languageserver-node#1531]
I found this issue from, it bump vscode-languageclient 8.0.1 -> 8.1.0
https://github.com/kcl-lang/vscode-kcl/pull/45

![image](https://github.com/user-attachments/assets/9ccaa612-753f-4f2e-b6a4-7f2c380e5b95)

Before this, in my lsp server, it always get these event in the order of `[completion, did_change]`.
But in 8.1.0, it change to `[did_change, completion]`.

When I try to change package.json from ^8.0.1 to 8.0.1, it turns to  `[completion, did_change]`.

So, I have two questions:
1. Is this an expected change, or a bug, or just my illusion?
2. When edit in VSCode, the order of these event is fixed or random? if fixed, what is the normal order?

Any reply will be very useful to me, thx

**Comment by dbaeumer** [comment]
When you type in the editor the order should be `[did_change, completion]` so that completions are calculated on the actual state of the file. If the user continues typing after the completion request is sent, but not answered yet, the client will cancel the current completion request and send a new one.

Do you see any issues with that order?

**Comment by He1pa** [comment]
I'm just not sure about the order.
Before this, it was always [completion, did_change], I thought it was the "correct" order, so I designed and implemented the lsp in this order.

request completion -> read complie result (read lock) and analysis comple item -> response -> did_change -> write lock -> (async) recompile and update complie result > unlock

But after this, it became
did_change -> write lock -> (async) recompile and update complie result > unlock -> request completion -> read complie result (read lock) and analysis comple item -> response

Because of the lock, I found that the completion request now always has to wait until the compilation is completed. It is a bit sluggish in VSCode.
There are some problems with my design that need to be modified.
But what confuses me is that the order was always [completion, did_change]. So, the same question, in 8.0.1, is this a bug, or is it just my illusion

**Comment by dbaeumer** [comment]
There were bugs in 8.x where changes weren't delivered in time before a language feature request was sent. But they should all be fixed, especially in the latest `10.0.0-next.10` client.

In general there isn't the one correct answer. It depends on in which order you do things in the editor. When you type and then request code completion the correct order is `[did_change, completion]`. Otherwise code completions will be generated on a wrong document state. 

However when you trigger code completion directly with the keyboard (Ctrl+Space) and then select an item which changes the text the order will be `[completion, did_change]`

**Comment by He1pa** [comment]
Thank you for your answer
