### ISSUE TITLE
make connection.onShutdown returns a Promise and wait before kill process.

### ISSUE THREAD

**Issue by richard1122** [Microsoft/vscode-languageserver-node#158]
I implemented an extension for youcompleteme. https://github.com/richard1122/vscode-youcompleteme

When shutdown vscode, an http request sent to `/shutdown` is required to shutdown other process that started by ycmd server.

Currently I could not send this request in connection.onShutdown() callback because the server process is killed so quickly after onShutdown called.

Please make connection.onShutdown returns an Promise and wait it before killing the language server process.

Thanks.

**Comment by dbaeumer** [comment]
We had a long discussion about this and we decided to do the following:

- on shutdown returns a promise
- we wait on it for ~500ms (I need to look up the correct number since we changed it lately)
- after 500ms are over we shutdown the extension host.

On Windows this takes down the language server as well. If you need more time than the budget we give extension then you can start the server in detached mode (currently needs to provide a start function). When in detached mode the server will stay alive even if VS Code is already shutdown and you can spent more time to clean up.

Which version of VS Code are you using. We implemented this behavior in one of the latest version of VS Code (I think 1.7)

**Comment by richard1122** [comment]
@dbaeumer 
Hi, I've tested to return a promise in `connection.onShutdown` and it works fine.

I'm using VSCode 1.10 and insiders it both works.

Thanks.

**Comment by dbaeumer** [comment]
Thanks for the feedback.
