### ISSUE TITLE
vscode-languageclient sends undocumented message '$/setTraceNotification'

### ISSUE THREAD

**Issue by smarter** [Microsoft/vscode-languageserver-node#170]
[lsp4j](https://github.com/eclipse/lsp4j) is unhappy about that:
```java
{
  "jsonrpc": "2.0",
  "method": "$/setTraceNotification",
  "params": {
    "value": "off"
  }
}
févr. 21, 2017 3:32:04 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
AVERTISSEMENT: Unsupported notification method: $/setTraceNotification
```

**Comment by svenefftinge** [comment]
This is because the other side doesn't know about that notification, and by default LSP4J will WARN about such ignored notifications. 
You should wither configure the logger to ignore it or register the missing notification type.

I think this can be closed here.

**Comment by smarter** [comment]
Sure, but it would be better if the message was documented in the protocol, and/or if there was a way to tell the client to not send the message.

**Comment by dbaeumer** [comment]
Actually $/setTraceNotification is an implementation details of our vscode-jsonrpc library. I din't want to document how tracing happens since this is very library dependent. What I should document is that these can be ignored. I added 

#### $ Notifications and Requests

Notification and requests ids starting with '$/' are messages which are protocol implementation dependent and might not be implementable in all clients or servers. For example if the server implementation uses a single threaded synchronous programming language then there is little a server can do to react to a '$/cancelRequest'. If a server or client receives notifications or requests starting with '$/' it is free to ignore them if they are unknown.
