### ISSUE TITLE
Semantics of CancelToken

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-languageserver-node#184]
Could you clarify what happens to the result promise if the request was canceled?
In C# you would get an `OperationCancelledException`, but looking at the code in vscode-jsonrpc, it seems like the promise is never resolved and pending forever. That seems like a bug to me

**Comment by felixfbecker** [comment]
This code here sends the `$/cancelRequest` but does not reject `result` promise a few lines above.:
https://sourcegraph.com/github.com/Microsoft/vscode-languageserver-node@e0cfdc96bb513809e6ac8aa239f27ce85b6e5615/-/blob/jsonrpc/src/main.ts#L799:1-800:1

That means if you have code like this:

```ts
// Do something that requires clean up afterwards like spawning a process, creating a temp file, opening a socket
const tmpFolder = await fs.mkdtemp(...);
try {
  await connection.sendRequest(params, token);
} finally {
  // Clean up
  await rimraf(tmpFolder);
}
```

The `finally` will never get executed and no clean up is done, which means the code will leak disk space / memory / file descriptors / processes / whatever and crash sooner or later.

**Comment by dbaeumer** [comment]
We can't through an exception or reject the promise since it is the servers responsibility to do that (it is speced in that way in the protocol). So the LSP client library for VS Code sends a `$/cancelRequest` request to the server. The server then needs to respond to the cancel request. It is up to each request to decided what to do on cancel. The server can either reject the request (error it and pass the new OperationCancelled error code) or resolve with a partial result if the client supports that or ignore the cancel request. 

In C# the `OperationCancelledException` is not thrown automatically either. The operation itself receives the cancel request as well (either through an event or through polling) and is free to decided what to do with the cancel request (it can ignore it as well if for example the operation knows it is 99,9% done anyways).

**Comment by felixfbecker** [comment]
Thanks for the explanation, makes sense. So I guess after every request I should throw myself if cancellation was requested.

What happens though if the `cancelRequest` cannot be sent because eg the underlying socket was already closed? Will the promise be rejected then?

**Comment by dbaeumer** [comment]
The jsonrpc library fires an event if the connection is closed. It is the up to the client of the library to decide what to do. Usually the client will call connection.dispose() which will error all outstanding request promises. 

However looks like the VS Code client doesn't do this in server crash cases correctly right now. It does on shutdown. Opened #187.
