### ISSUE TITLE
Return type of SignatureHelp is incompatible with the protocol

### ISSUE THREAD

**Issue by tomv564** [Microsoft/vscode-languageserver-node#191]
The `activeSignature` and `activeParameter` fields of SignatureHelp should be optional, as described in:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#signature-help-request

See: https://github.com/Microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L971-L979
Can provide PR if needed. Thanks!

**Comment by dbaeumer** [comment]
Actually the comments of the spec should be updated here. The problem is that these can't be optional that is why we are not allowing them to be optional in the node implementation for VS Code. For compatibility the client still handles the case when they are missing and uses 0. However server should think about these two fields and not simply leave them undefined.

Do you want to provide a PR to clear this in the spec?

**Comment by tomv564** [comment]
Thanks for replying! I understand you are using the stricter typing to force service implementers to send complete responses, it is unfortunate that the value `0` could be interpreted by clients that there is at least one signature in the array.

It would be great if you could update the spec and add your suggestion for the empty response.

**Comment by felixfbecker** [comment]
@dbaeumer Is there any reason why they can't be optional?

**Comment by dbaeumer** [comment]
Tools are using the information to highlight the 'active' parts in the UI. If the result is of length 1 then 0 is a good default however if the result is > 1 then 0 is bad. The server needs to make a decision here. This is why I think they should not be optional. They are currently since I don't want to break the protocol for this change.

**Comment by felixfbecker** [comment]
but what if a method has no parameters? setting `activeParameter` to `0` if the `parameters` array has element zero sounds semantically incorrect and could cause out of bound exceptions in clients that expect it to be undefined in that case

**Comment by dbaeumer** [comment]
That is a good point. We could either say -1 or undefined. The problem with undefined is that implementers tend to leave optional things out and therefore the UI results in bad rendering. I will update the spec accordingly.

**Comment by dbaeumer** [comment]
OK. Thinking about it more I spec it that way: if the index lies outside the length of the array it is treated as 0.

**Comment by dbaeumer** [comment]
I updated the spec. On the node implementation side I allow null to actively indicate that for example the active signature has no parameters.
