### ISSUE TITLE
@types/node prevents building ts files

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode-languageserver-node#194]
I've run into a problem with using the vscode-languageclient package in typescript projects. When building the project via tsc, I get a bunch of errors that the vscode-* packages can't find type definitions for node. This makes sense because "@types/node" is listed as a devDependency of vscode-languageclient and vscode-jsonrpc packages. Therefore `npm install` won't install devDependencies of a dependency (unless using the `--dev` option which I'm told is deprecated).  As such, unless I add "@types/node" to my project's devDependencies, I can't build the project. Can you please confirm that this is the expected behavior or if this should be dealt with differently.

For repro, I've built a small node project that will show off the issue. Please see this gist for the input and output. https://gist.github.com/benrr101/12acfaee8c51c54e6fd08c4779802b64

**Comment by dbaeumer** [comment]
@benrr101 we are aware of this and the recommended way to deal with this is to add @types/node to your dev dependencies.

We decided to do this since the alternative would be to list @types/node as a real dependencies hence installing the typings even if you use the module as a normal npm dependency.

I will close the issue since the other behavior will even cause more confusion. And usually people developing with TS using npm package do have @types/node as a dev dependency.

**Comment by benrr101** [comment]
Understood. We ended up having issues after adding the @types/node package as a dev dependency because we also had a static node.d.ts file in our typings folder. Removing that, adding @types/node and tweaking the code that depended on the typings fixed the issue for us.

Apologies then for spam tickets -- I wasn't entirely clear on the particulars around typings.

**Comment by dbaeumer** [comment]
@benrr101  No problem.
