### ISSUE TITLE
Accessing ServerCapabilities

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode-languageserver-node#204]
Servers can provide experimental capabilities on initialize. It would be nice to access them and register additional feature handlers before a ready promise is resolved.

**Comment by dbaeumer** [comment]
Nice idea. We need to decide whether we only want to expose the capability literal or the way how the client handles features. The second would give them the dynamic registration for free, but would be more API.

**Comment by akosyakov** [comment]
Looking closer there is also no way to provide experimental client capabilities, only initialization options.

**Comment by dbaeumer** [comment]
Correct.

**Comment by DanTup** [comment]
I don't know if it's the same request as this - I'm trying to migrate to LSP and I need my VS Code plugin to disable it's "built-in" support for features if the LSP server is handling them. Is this currently possible?

For example, I want to know if the LSP server said it supports hover or document formatting.

**Comment by dbaeumer** [comment]
@DanTup the client has this information, but it is currently not exposed as API. See https://github.com/Microsoft/vscode-languageserver-node/blob/dbaeumer/projectReferences/client/src/client.ts#L2365

**Comment by DanTup** [comment]
@dbaeumer Are there any simple workarounds? (or would you accept a PR that makes that field public - or do you want to control access to it better?)

**Comment by dbaeumer** [comment]
Actually this has improved in the meantime. You can register features with a client and the feature gets the server capabilities passed into its `initialize` call. When registering a feature it is not supposed to register against the VS Code API. A feature does this in the initialize call depending on the server capabilities.

There is still no public API to access the server capabilities. I will however accept a PR to expose it.

Closing the issue since IMO the original request is now working
