### ISSUE TITLE
vscode-languageserver 3.3.0+ can't process connection via stdio expectedly

### ISSUE THREAD

**Issue by vvakame** [Microsoft/vscode-languageserver-node#236]
I updated vscode-languageserver 3.2.2 to 3.3.0.
My test script uses `--stdin` option.
test script works fine in v3.2.2, but v3.3.0 is not.
Sorry, I can't investigate what change was occurred this issue.

Reproduction environment. `yarn && npm run vscode:update && npm run build && npm run test`.
https://github.com/prh/prh-languageserver/commit/9630330f39063c588d6533e5acf33e204b67e199
Test script.
https://github.com/prh/prh-languageserver/blob/9584c0944b32e6f50c4ac7b753059c1b77ca961a/package.json#L14

I am glad if there is information on how to make a good test for language server.

**Comment by dbaeumer** [comment]
I think this fails since the client and server share the same handles from the parent process. This was never expected to work.

You can debug this by starting the server in break mode and see why the stream doesn't work anymore. Alternatively you could look at the connection.test.ts file in the jsonrpc module. This one uses Duplex streams to run a 'client' and 'server' in the same process (in terms of a connection).
