### ISSUE TITLE
vscode-languageclient 3.4.2 can't be compiled against vscode 1.1.5

### ISSUE THREAD

**Issue by alexi2014** [Microsoft/vscode-languageserver-node#248]
vscode-languageclient 3.4.2
vscode 1.1.5

I get the following compilation error in the node_modules\vscode-languageclient\lib\client.d.ts file, in the following import statement:
import { ........, **WorkspaceFolder** as VWorkspaceFolder } from 'vscode';
error TS2305: Module ''vscode'' has no exported member 'WorkspaceFolder'.

I checked the imported node_modules\vscode\vscode.d.ts file and found that the WorkspaceFolder symbol is not really exported from this module.

**Comment by dbaeumer** [comment]
This is correct and on purpose. That is why the client list vscode 1.16 as a prerequisite. If you need to compile against 1.15 you need to stick with 3.3.x. The thing is that the new npm modules provide support for new API in VS Code (e.g. workspace folders and configuration) and therefore prereq 1.16.

1.16 got release yesterday :-)

**Comment by alexi2014** [comment]
Thanks for the clarification!
Just want to pay your attention to the fact that package.json of vscode-languageclient 3.4.2 proclaims dependency on vscode 1.1.5 :
  "devDependencies": {
    "vscode": "^1.1.5"
  },

And vscode 1.1.5 is the maximal available version on npm.

**Comment by adamvoss** [comment]
@alexi2014 If I understand correctly, here it is the `engines` section of your package.json that would need to change:
```json
  "engines": {
    "vscode": "^1.16.0"
  },
```

@dbaeumer This also broke my CI build.  I'm not sure that there was any better way to handle this within the npm ecosystem so maybe this was the best possible experience.  However, I am reporting that is an undesirable developer experience for semver compatible package update to break a build.

**Comment by dbaeumer** [comment]
@alexi2014 `"vscode": "^1.1.5"` is the dependency for the VS Code extension developer pack. It is not the runtime version of VS Code. This is the one pointed out by @alexi2014.

@adamvoss I see your point and we discussed this. The underlying problem is that the runtime dependency changed and this can't be expressed nicely (e.g. the runtime is no 'dependency' which gets installed via npm install). From an semver API perspective LSP 3.4.0 is still backwards compatible but not from a runtime perspective. I we move the major version number every time the VS Code runtime changes it would be very confusing as well.
