### ISSUE TITLE
Installing server fails if package.json uses relative file dependencies

### ISSUE THREAD

**Issue by martin-slater** [Microsoft/vscode-languageserver-node#267]
I am trying to resuse a local node module between client and server using file: dependencies in the package.json, i.e.

```
  "dependencies": {
    "vscode": "^1.1.5",
    "vscode-languageserver": "^3.4.2",
    "my-local-module": "file:../my-local-module",
  }

```
this works fine for building the server but after the package.json has been copied to the client/server directory and `npm update --production --prefix ...` is run it obviously breaks.  I am trying to avoid moving the package into a seperate git repo and referencing it from there, could you suggest how I could possibly make this work without modifying installServerIntoExtension to read the package.json, rebase relative dependencies and then write again?

thanks,  Martin.

**Comment by dbaeumer** [comment]
@martin-slater you could do what the vscode-eslint extension does. Instead of having the client containing the server the extension itself contains both the client and server code. However this requires some tricks when building the vsix for the market place (you need to specify special exclude rules; otherwise you package contains unnecessary code).

See https://github.com/Microsoft/vscode-eslint and especially https://github.com/Microsoft/vscode-eslint/blob/master/.vscodeignore

**Comment by martin-slater** [comment]
@dbaeumer Many thanks for the suggestion Dirk, that looks like it will work well.
