### ISSUE TITLE
Implications for privacy and confidentiality

### ISSUE THREAD

**Issue by joaocc** [Microsoft/vscode-languageserver-node#277]
Hi,
I have been trying to find information on the possible implications on privacy and confidentiality from using language server.
From my (assumedly incomplete) understanding, having some information being sent to a remote server while you code, with that information being all the code or only semantic information, creates a information security risk for data leaks, source code theft and other non-trivial questions. Also, I have found no information on how to disable language servers as a whole in vscode. 
I would appreciate it if someone could point me to relevant documentation or discussions about this topic.
Thanks

**Comment by dbaeumer** [comment]
@joaocc you need to contact the tool and or extension owners about this since language servers don't exist by themselves. I a default VS Code installation for example (with any third part extensions I can't speak about) all language servers run locally on your machine. So there is not information flowing to a remote server.

**Comment by joaocc** [comment]
@dbaeumer Thanks for your clarification. Is there any documentation or discussions that address what type of information is sent to language-servers and how to identify which language servers may be sending information to a remote location?

**Comment by dbaeumer** [comment]
No, this is something an extension or the tool need to provide. Language servers itself like the tool have access to the content of the file system when run locally.
