### ISSUE TITLE
Client sends textDocument/didOpen for QuickDiffProvider original source

### ISSUE THREAD

**Issue by sam-mccall** [Microsoft/vscode-languageserver-node#289]
We use a SCM extension (unfortunately not public) that provides a QuickDiffProvider that looks like this:

    provideOriginalResource(uri: vscode.Uri, token: vscode.CancellationToken):  vscode.ProviderResult<vscode.Uri> {
      return uri.with({
        scheme: 'piper',
        authority: 'baseline',
        path: '/' + uri.fsPath,
      });
    }

The intent is that these URIs are only used by VSCode to provide the baseline content of a file in source control.

When we open a file, our LSP server (`clangd`) receives `textDocument/didOpen` events for these `piper://` URIs!
This results in:
 - confusion because we can't work out how such files should be interpreted/build (in general this requires traversing the source tree on the filesystem)
 - unneccesary work if we do manage to work out how to build these files - e.g. we need to run a second copy of our build system the baseline vs current version have different build configurations in general

From our point of view, it'd be much preferable if Quickdiff original resources were never sent to LSP and treated as textual only (or at least LSP flagged them somehow so our server could choose to ignore them).

**Comment by rcjsuen** [comment]
@sam-mccall I've heard of such problems with URIs in the past. You may be interested in Microsoft/vscode#21526 and Microsoft/vscode#20859.

**Comment by dbaeumer** [comment]
This can actually be control by the extension starting the language server. The LSP client module allows to provide document selectors. So the clangd code that creates the LSP client would say that onle 'file' and 'untitled' schemas should be synced.

There is nothing that the LSP can do in general here besides giving clients control over this. There might be a sever being interesting in something different than 'file' and 'untitled' so I can not filter them by default. 

I close the issue since this is outside the LSP scope. If VS Code itself decided to filter schemas or to provide and opt in support the LSP client will profit from it automatically.

**Comment by sam-mccall** [comment]
@dbaeumer The URI scheme is a red herring, I think (sorry I explained poorly).

We noticed the problem because of the weird URIs, but the same problems would exist if the SCM plugin returned `file://` (and in fact for our Piper plugin this would be a reasonable choice - I guess there are SCM plugins that do this).

I wasn't sure which project this belongs to, but it seems like VSCode could communicate the semantic distinction between opening for view and fetching for diff, and the LSP client should only examine the former...

For this particular combination of plugins, we do have a workaround though, thanks!

**Comment by dbaeumer** [comment]
VS Code has an item so that the LSP client could determine whether a file was opened for content reading only (as a text buffer) or is opened in the editor. But it doesn't exist right now so all the LSP client can do is to treat reads as open.
