### ISSUE TITLE
Help on implementing the language server in another language

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-languageserver-node#30]
I would like to write a language server for PHP. There are great PHP libraries for parsing PHP into an AST and for parsing doc blocks. I started off by implementing it as a normal VS Code extension and calling a little PHP script that returned the AST in JSON, which I would then traverse in TypeScript. But that means I have to duplicate so many classes and interfaces, duplicate code for pretty-printing and traversal that is already bundled in the original library, etc... I figured the best option would be to make it a language server, implemented in PHP. Unfortunately, I did not find any documentation of the protocol that VS Code speaks to a language server. There is only this repository with the TypeScript implementation, but that of course cannot be ported 1:1 to PHP. Could you please provide me with some info about the protocol?

**Comment by dbaeumer** [comment]
@felixfbecker working on a documentation in mark down.

What also helps a lot is the following file: https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/protocol.ts

It is basically the protocol in terms of TS interfaces.

**Comment by dbaeumer** [comment]
@felixfbecker let me know if you need any short term support. I am happy to answers questions.

**Comment by dbaeumer** [comment]
@felixfbecker: besides the server protocol you need to know the base json-rpc protocol. The definition looks like this:

## Base Protocol

The base protocol consists of a header and a content part (comparable to http). The header and content part are
separated by a '\r\n'.

### Header Part

The header part consist of header fields. Header fields are separated from each other by '\r\n'. The last header
field needs to be terminated with '\r\n' as well. Currently the following header fields are supported:

| Header File Name | Value Type  | Description |
|:-----------------|:------------|:------------|
| Content-Length   | number      | The length of the content part |
| Content-Type     | string      | The mime typ of the content part. Defaults to application/vscode-jsonrpc; charset=utf8 |

The header part is encoded using the 'ascii' encoding. This includes the '\r\n' separating the header and content part.

### Content Part

Contains the actual content of the message. The content part of a message uses [JSON-RPC](http://www.jsonrpc.org/) to describe requests, responses and notifications. The content part is encoded using the charset provided in the Content-Type field. It defaults to 'utf8'. Due to the limitation of Node.js only the following encodings are supported right now: 'ascii', 'base64', 'binary', 'hex', 'utf8', 'utf16le'. 


### Example:

```
Content-Length: ...\r\n
\r\n
{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "textDocument/didOpen", 
	"params": {
		...
	}
}
```
### Base Protocol JSON structures

The following TypeScript definitions describe the JSON-RPC protocol as implemented by VSCode:

#### Abstract Message

A general message as defined by JSON-RPC. The language server protocol always uses "2.0" as the jsonrpc version.

```typescript
interface Message {
	jsonrpc: string;
}
```
#### RequestMessage 

A request message to decribe a request between the client and the server. Every processed request must send a response back to the sender of the request.

```typescript
interface RequestMessage extends Message {

	/**
	 * The request id.
	 */
	id: number | string;

	/**
	 * The method to be invoked.
	 */
	method: string;

	/**
	 * The method's params.
	 */
	params?: any
}
```

#### Response Message

Response Message send as a result of a request. 

```typescript
interface ResponseMessage extends Message {
	/**
	 * The request id.
	 */
	id: number | string;

	/**
	 * The result of a request. This can be omitted in
	 * the case of an error.
	 */
	result?: any;

	/**
	 * The error object in case a request fails.
	 */
	error?: ResponseError<any>;
}

interface ResponseError<D> {
	/**
	 * A number indicating the error type that occured.
	 */
	code: number;

	/**
	 * A string providing a short decription of the error.
	 */
	message: string;

	/**
	 * A Primitive or Structured value that contains additional
	 * information about the error. Can be omitted.
	 */
	data?: D;
}

export namespace ErrorCodes {
	export const ParseError: number = -32700;
	export const InvalidRequest: number = -32600;
	export const MethodNotFound: number = -32601;
	export const InvalidParams: number = -32602;
	export const InternalError: number = -32603;
	export const serverErrorStart: number = -32099
	export const serverErrorEnd: number = -32000;
}
```
#### Notification Message

A notification message. A processed notification message must not send a response back. They work like events.

```typescript
interface NotificationMessage extends Message {
	/**
	 * The method to be invoked.
	 */
	method: string;

	/**
	 * The notification's params.
	 */
	params?: any
}
```

The corresponding TS file defining it is here: https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/messages.ts

Hope that gets you started.

**Comment by felixfbecker** [comment]
@dbaeumer Thank you for your detailed description of the protocol. Maybe you can give me an example how would a typical sequence look like for a language server, for example for IntelliSense, or getting notified when a file changed? And what exactly is "the method to be invoked"?

**Comment by dbaeumer** [comment]
@felixfbecker: you can find a more detailed doc here https://github.com/Microsoft/vscode-languageserver-protocol. It is documented in a request / response form like REST APIs are documented. Let me know if this helps. One thing I would like to add there as well is some sequence diagrams for typically request / response flows.

**Comment by dbaeumer** [comment]
Closing this since the documentation is tracked in https://github.com/Microsoft/vscode-languageserver-protocol
