### ISSUE TITLE
setting Capabilites

### ISSUE THREAD

**Issue by willt** [Microsoft/vscode-languageserver-node#306]
I'm at a complete loss on how to set client capabilities. I'm trying to set this one so I can send versioned edits. WorkspaceClientCapabilites.workspaceEdit.documentChanges

My client more or less looks like the one here: https://code.visualstudio.com/docs/extensions/example-language-server
I've spent a few hours search and digging I just can't figure it out.
Non versioned edits work fine using 'changes' instead of 'documentChanges'
I'm about to give up on versioned edits :(

In case it wasn't clear this is for the client portion of a language server im writing for vscode.

Running vscode 1.19.3
Thanks!

**Comment by rcjsuen** [comment]
Hi, @willt.

So if I understand correctly, your language server is initialized properly but the initialization parameters being sent to your language server from VS Code doesn't have `params.capabilities.workspace.workspaceEdit.documentChanges` set to `true`. And so you want to set it yourself, correct?

**Comment by rcjsuen** [comment]
Thank you for confirming, @willt. It seems you have stumbled upon the same problem as #263 where the capability was commented out in 863685b0dc160345bb91d7f7bac84cc6b89d8153 and mistakenly removed in 4bc789ecfca9af5f98188e42ee3302dae2b2a5aa.

I have opened #307 which should fix your problem as it changes VS Code's LSP client to declare `clientCapabilities.workspace.workspaceEdit.documentChanges` as `true`.

As a workaround, please use the code below in your VS Code extension to explicitly massage the initialization parameters to include the capability.

```TypeScript
import { StaticFeature } from 'vscode-languageclient';
export class WorkaroundFeature implements StaticFeature {
    fillClientCapabilities(capabilities): void {
        capabilities.workspace.workspaceEdit = { documentChanges: true };
    }
    initialize(): void {
    }
}
```
```TypeScript
let client = new LanguageClient(/* your code */);
client.registerFeature(new WorkaroundFeature());
```

I do want to make it clear however that your original goal of manually changing the initialization parameters is not a good idea. It is not a problem in this case because VS Code actually [supports this capability](https://github.com/Microsoft/vscode-languageserver-node/blob/f4595fa4f3a52c9210792c7b412f9e2ee478cdd3/client/src/client.ts#L2945-L2955) so manually toggling the flag will achieve what you want. However, consider the scenario where there is a feature that your language server supports but VS Code doesn't. You change the parameter to `true` and now your server will start sending stuff to VS Code back in a form that VS Code doesn't understand as if VS Code supports this feature when it actually doesn't.

Consider the operating system's recycle bin feature. The OS says it can't put things in the bin but you've changed it to say it does. Now client applications will prompt the user "Okay to put it in the bin?" and subsequently start asking the OS to put files and folders in the recycling bin when it actually doesn't work. If the OS instead decides to simply honour the API call by outright deleting the file then you have caused your users to lose data. This analogy might be a bit "out there" but I hope it illustrates why your original means to your desired end was incorrect.

**Comment by dbaeumer** [comment]
@rcjsuen very nice and correct analysis. Will merge you PR.

**Comment by willt** [comment]
@rcjsuen Thank you so much. The only reason I went down the path of setting the capabilities is because it wasn't set and from looking at the source it seemed like it should have been.
Glad to know it was a bug and I understand your warning. Thanks again!
