### ISSUE TITLE
Make ResponseError available to middleware

### ISSUE THREAD

**Issue by bmewburn** [microsoft/vscode-languageserver-node#315]
It would be useful if `ResponseError` was available to `WorkspaceMiddleware` so that custom errors could be handled appropriately. The specific use case I have in mind is detailed in Microsoft/vscode#43538.

**Comment by dbaeumer** [comment]
The middle ware API is defined usinb VS Code API types not LSP API types. The reason for this is to allow intercepting the calls as early as possible and because the client is VS Code specific. So the middle ware signatures by itself can't have a ResponseError type. However we could look into whether we add additional callbacks to intercept them.
