### ISSUE TITLE
Language client should restart server after crash.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-languageserver-node#34]

**Comment by daviwil** [comment]
This could be a little problematic if the language server is crashing consistently on startup.  If it's possible, you might want to stop attempting a restart if the server crashes something like 5 times within 2 minutes.

**Comment by sridmad** [comment]
Agree. VC language server in VS is OOP and has auto recovery. Stops trying to restart the server on the same source file (since a specific source file could be crashing it) for the VS session if it crashes more than a couple of times or within a certain period of restart

**Comment by dbaeumer** [comment]
This is what I had in mind since we do the proposed for the tsserver. If the tsserver crashes 5 times in a row we don't even attempt to restart. If it crashes 5 times in a minute we ask the user to open an issue on github. 

I can implement the above default strategy and also allow to plug in something custom into the client. Would that satisfy your needs?

**Comment by sridmad** [comment]
Default strategy sounds fine. At this point I don't see C++ extension needing a different strategy we just need one.

**Comment by daviwil** [comment]
Yep, the default sounds fine for me too!

**Comment by daviwil** [comment]
I just remembered one more thing.  When I'm working on my language server and testing changes in VS Code, I need to kill it so that I can recompile the host exe without VS telling me that it's in use.  Could you provide a flag in the LanguageClient to disable restart behavior so that I can use that when I've got the extension in developer mode?

**Comment by dbaeumer** [comment]
I pushed changes to master that restarts the server. I haven't published new npm modules since I first wanted to get your feedback.

The strategy an be configured via a new property on the client options called errorHandler. If no handler is provided a default handler is used that restarts the server unless it died 5 times in the last 3 minutes.

**Comment by dbaeumer** [comment]
Closing as implemented. Please ping if you see issues with the current implementation.

**Comment by damieng** [comment]
If you have to restart the language servers whenever they die perhaps that information belongs in the spec?

**Comment by dbaeumer** [comment]
@damieng I am reluctant to add this to the spec. I would argue that this is the decision of the client. We for example don't restart if the server crashes frequently.

**Comment by damieng** [comment]
I wonder then if a separate implementation notes doc would be a good idea?  There are a few things that are kind of out of spec that would be useful to have documented somewhere to avoid confusion for other implementers (I've spent a fair amount of time looking into crashing servers that "don't crash with vscode" which I now suspect is because of the auto-restart code).

Another example is knowing when to end autocomplete given the spec only talks about trigger characters but not about ending characters for when no option is chosen (e.g.  `(`  )

**Comment by dbaeumer** [comment]
@damieng a implementation document makes sense to me, however it should happen here: https://github.com/Microsoft/language-server-protocol. Also the auto complete issue should be tracked there.
