### ISSUE TITLE
Implement hierarchical document outline

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-languageserver-node#373]

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode-languageserver-node/tree/dbaeumer/373

**Comment by Gama11** [comment]
I've started playing around with this branch in the Haxe language server, working well so far. 👍 

One question: is `selectionRange` implemented yet? Picking a symbol from <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd> moves the cursor to the start of `range` (rather than `selectionRange` as I would have expected). For instance in this case, the `selectionRange` is `foo`, yet the cursor is positioned before `public` which is where `range` starts:

![](https://i.imgur.com/570WVSK.gif)

**Comment by dbaeumer** [comment]
The selectionRange is used to denote what to do if the cursor moves into the range. In VS Code for example we then select the symbol in the outline. So it is not what the editor selects it is the range the editor is sensitive to the symbol when its selection moves in.

**Comment by Gama11** [comment]
Hm.. I thought that's what `range` is for?

>The range enclosing this symbol not including leading/trailing whitespace but everything else like comments. **This information is typically used to determine if the the clients cursor is inside the symbol to reveal in the symbol in the UI.**

**Comment by dbaeumer** [comment]
Sorry. You are correct. I got confused myself.

**Comment by dbaeumer** [comment]
And yes that should be implemented. It is converted as follows:

```
		let result = new code.DocumentSymbol(
			value.name,
			value.detail,
			asSymbolKind(value.kind),
			asRange(value.range),
			asRange(value.selectionRange)
		);

```

can you reproduce this using a non LSP based example?

**Comment by Gama11** [comment]
Yes, this seems more like a VSCode issue: https://github.com/Microsoft/vscode/issues/54857

**Comment by dbaeumer** [comment]
Thanks for testing. I created a new version today which as not official support for document symbol.
