### ISSUE TITLE
Confusing naming of createClientSocketTransport/createServerSocketTransport

### ISSUE THREAD

**Issue by uebayasi** [Microsoft/vscode-languageserver-node#377]
To me (who is not a native English speaker), they are confusing.  I believe that they should be named inversely.  Now `createServer` is wrapped by `createClientSocketTransport`; why not by `createServerSocketTransport`?

Same for `create{Client,Server}PipeTransport`.

**Comment by dbaeumer** [comment]
This is intentional. `createClientSocketTransport` create the socket transport for the LSP client side and `createServerSocketTransport` for the LSP server side.

Internally `createClientSocketTransport` now internally creates a net.Server. Reason is that this avoids any timing issues since the LSP client will later start the server process and hence the server process can easily connect to the net.Server.

If the connection would go to a remote server then link would look different and a different `createRemoteSocketTransport` would be needed.

I am closing the issue. Please ping if the explanation didn't make sense.
