### ISSUE TITLE
Register proposed feature in the base language client

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode-languageserver-node#386]
Is there any reason for not doing it?

**Comment by aeschli** [comment]
@akosyakov Can you elaborate?

**Comment by akosyakov** [comment]
[BaseLanguageClient](https://github.com/Microsoft/vscode-languageserver-node/blob/5f9c993ff38f5c369949aeb359b3e9b178172dbc/client/src/client.ts#L2245) was introduced in https://github.com/Microsoft/vscode-languageserver-node/pull/148 to be agnostic to Node.js/Electron and be reused in the browser.

It registers builtin features but missing proposed: https://github.com/Microsoft/vscode-languageserver-node/blob/5f9c993ff38f5c369949aeb359b3e9b178172dbc/client/src/client.ts#L2923-L2948

I wonder whether it is on purporse. In monaco-languageclient we had to redeclared them.

**Comment by dbaeumer** [comment]
Yes this is on purpose since it would otherwise introduce cyclic dependencies. A feature needs a language client (BaseLanguageClient). 

As I already commented in other place the `BaseLanguageClient` is NOT Node nor VSCode agnostic since it depends on the protocol which depends on JSON-RPC. It somehow worked for some cases but if we really want to have a client that is runtime agnostic more engineering work is necessary.

To break the above cyclic dependency the BaseLanguageCLient must be a maintained interface which it currently isn't.

Any objection to close the issue. If we want to have a full runtime agnostic client then we need to have a separate item to work on.
