### ISSUE TITLE
initializationFailedHandler API fallback

### ISSUE THREAD

**Issue by divyenduz** [Microsoft/vscode-languageserver-node#463]
Currently, providing an `initializationFailedHandler` that returns `true` causes the extension to try an [initialize itself infinitely](https://github.com/Microsoft/vscode-languageserver-node/blob/931b9ad18f50a4103f2a6d11d399557db8cb1dec/client/src/client.ts#L2839-L2840). Is this behavior intentional? 

I wanted to raise this because I think it is easier to get using this API wrong https://github.com/prisma/vscode-graphql/issues/89

Here are a few suggestions, I am more than happy to implement them:

1. Do an exponential backoff even if this behavior is intended? 
2. Implement safe defaults like the [DefaultErrorHandler](https://github.com/Microsoft/vscode-languageserver-node/blob/931b9ad18f50a4103f2a6d11d399557db8cb1dec/client/src/client.ts#L273-L286).
3. Warn the user that their extension is initializing infinitely somehow.

**Comment by dbaeumer** [comment]
This is on purpose but I do see the need to clarify this in the documentation. I added

```
/**
 * A handler that is invoked when the initialization of the server failed.
 */
export interface InitializationFailedHandler {
	/**
	 * @param error The error returned from the server
	 * @returns if true is returned the client tries to reinitialize the server.
	 *  Implementors of a handler are responsible to not initialize the server
	 *  infinitely. Return false if initialization should stop and an error
	 *  should be reported.
	 */
	(error: ResponseError<InitializeError> | Error | any): boolean;
}
```

Implementing a reasonable default is IMO not possible since the client can not know what to change to make the initialization go through the next time. Usually clients need to adjust some settings to make it go through the next time. This is different with the `DefaultErrorHandler` which is invoked when the server crashes.  

I will close the issue. Please ping if you strongly disagree.
