### ISSUE TITLE
filterText requires trimmed prefixes

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#488]
In `gopls`, we originally did not set filterText for completions, but we encountered an issue that required us to return prefix-trimmed filter text. I wonder if we could do the prefix-matching client-side, since none of the other editors seem to require prefix-trimmed filter text.

Repro case:

I have 2 variables in scope `item` and `insertText`. Without filter text, I type `i` and get suggestions for both variables. Then, I add the `t` and only see suggestion for `insertText` because of the filtering on the label. However, when I set filterText with trimmed prefixes (`tem` and `nsertText`), the behavior is as I would expect, i.e., both variables are matched.

Relevant issues: https://github.com/golang/go/issues/31552, https://github.com/Microsoft/language-server-protocol/issues/729, https://github.com/tigersoldier/company-lsp/issues/103.

**Comment by dbaeumer** [comment]
@stamblerre here is what I see with a simple example without any need of a filter text. 

![cast](https://user-images.githubusercontent.com/1931590/56725964-25280300-674e-11e9-8ce0-9043fdca55b9.gif)


Could you provide me with a test case that demos what you are seeing so I can investigate whether this is a problem in the LSP or the VS Code API. 

The code I use looks as follows:

```ts
			completionProvider: {
				triggerCharacters: ['.'],
				resolveProvider: true
			}
```
```ts
connection.onCompletion(
	(_textDocumentPosition: TextDocumentPositionParams): CompletionItem[] => {
		// The pass parameter contains the position of the text document in
		// which code complete got requested. For the example we ignore this
		// info and always provide the same completion items.
		return [
			{
				label: 'item',
				kind: CompletionItemKind.Text,
				data: 1
			},
			{
				label: 'insertText',
				kind: CompletionItemKind.Text,
				data: 2
			}
		];
	}
);
```

**Comment by stamblerre** [comment]
Here's my repro case:

![filter-text2](https://user-images.githubusercontent.com/5856771/56740991-03278400-6740-11e9-940e-aff5c1404abe.gif)

There is only ever one completion request - the second keystroke does not cause a second request to happen, I think it just filters the results of the first one. The completion items for `insertText` and `item` are:

```
{"label":"insertText","kind":6,"detail":"string","preselect":true,
"sortText":"00000","insertTextFormat":2,
"textEdit":{"range":{"start":{"line":8,"character":2},
"end":{"line":8,"character":2}},
"newText":"nsertText"}}
```
and

```
{"label":"item","kind":6,"detail":"protocol.CompletionItem",
"sortText":"00001","insertTextFormat":2,
"textEdit":{"range":{"start":{"line":8,"character":2},
"end":{"line":8,"character":2}},
"newText":"tem"}},
```

**Comment by dbaeumer** [comment]
If you want to have completion requests for every key stroke mark the completion result as incomplete (see https://github.com/Microsoft/vscode-languageserver-node/blob/master/types/src/main.ts#L1542)

Would you be able to provide code that can be executed that demos this (best a GitHub repository I can clone). You could even try to create a test case using native VS Code API. I am pretty sure it demos there as well since the LSP client does mostly only type conversion.

**Comment by stamblerre** [comment]
The code for this in `gopls`, which can be cloned by running: `go get -u golang.org/x/tools/cmd/gopls`. The code for building a completion item is specifically in this [file](https://github.com/golang/tools/blob/master/internal/lsp/completion.go), in the `toProtocolCompletionItems` function. It's reproducible if you comment out [line 75](https://github.com/golang/tools/blob/45abd401336eb55908f4883f98c1228a0181d91b/internal/lsp/completion.go#L75).

I had assumed that `isIncomplete` was for a scenario when you had too many possibilities to send a full list, and so you only sent some portion of the results, but perhaps I misunderstood?

**Comment by muirrn** [comment]
The problem seems to be related to triggering the completion with the start of an identifier rather than triggering with a ".". Triggering completion with "." works as expected.

In @stamblerre's example, if you accept the "insertText" item, it ends up inserting the entire label, leaving "iinsertText" (even though the completion item from gopls has "nsertText"). VSCode seems to not be using the gopls completions at all in this case (?). 

As another data point, setting isIncomplete=true makes to work as expected, but it is not clear to me why the client side filtering with isIncomplete=false doesn't work.

**Comment by dbaeumer** [comment]
Regarding `isComplete`: if true (the default) then the client can assume that the list is complete at the current cursor position and typing another character doesn't change the list. So the filtering can happen on the client side (which is a lot faster). If set to false typing a character can change the list and the client will contact the server again and the server could add additional items.

@stamblerre would you be able to make this reproduce in the following reppository: https://github.com/dbaeumer/vscode-lsp-488. It is a miniaml test case for your problem using a server written in TS. It offers code complete for text files.

**Comment by stamblerre** [comment]
I tried filling in the completion items with the other fields, and I set the trigger character to `'i'`, but I wasn't able to reproduce the issue with the text files.

```
		return [
			{
				label: 'item',
				kind: CompletionItemKind.Text,
				detail: 'string',
				sortText: '00000',
				insertTextFormat: InsertTextFormat.Snippet,
				textEdit: {
					newText: "tem",
					range: {
						start: {
							line: 1,
							character: 2,
						},
						end: {
							line: 1,
							character: 2,
						},
					},
				},
			},
			{
				label: 'insertText',
				kind: CompletionItemKind.Text,
				detail: 'string',
				sortText: '00001',
				insertTextFormat: InsertTextFormat.Snippet,
				textEdit: {
					newText: "nsertText",
					range: {
						start: {
							line: 1,
							character: 2,
						},
						end: {
							line: 1,
							character: 2,
						},
					},
				},
			}
```

However, I also noticed that it wasn't obeying the `sortText` property - `insertText` was always ranked above `item`.

Is it possible that there is some configuration in VSCode or the VSCode Go extension that would cause the filtering to change?

**Comment by dbaeumer** [comment]
The only once I am aware of are:

<img width="524" alt="capture" src="https://user-images.githubusercontent.com/1931590/57298532-beea9b00-70d2-11e9-845c-9343d1c6d097.png">

but they should not filter out items.

@jrieken do you have an idea why items wouldn't show up / get filtered?

**Comment by jrieken** [comment]
This is related to the range returned, e.g the prefix `i` isn't selected to be overwritten with `item` or `insertText` but the `i` is kept a concatenated with `tem` or `nsertText`. The consequence is that the `i` isn't used for scoring/highlighting. 

You seems to be trying many things like incomplete result sets, trigger characters, sort/filter text etc etc. That makes it hard to understand this issue... Can you create a simple dummy extension and steps how to use it so that I can repro this?

**Comment by muirrn** [comment]
> the prefix i isn't selected to be overwritten

Yes, that seems to be related. I patched gopls to overwrite the "i" instead of appending to it and the completion works as expected.

I reproduced the behavior in @dbaeumer's test project with the below stub completions. In particular, typing "it" only gives a completion for "insertText" instead of "item" and "insertText".

```
return [
	{
		label: 'item',
		kind: CompletionItemKind.Text,
		textEdit: {
			newText: "tem",
			range: {
				start: {
					line: 0,
					character: 1,
				},
				end: {
					line: 0,
					character: 1,
				},
			},
		},
	},
	{
		label: 'insertText',
		kind: CompletionItemKind.Text,
		textEdit: {
			newText: "nsertText",
			range: {
				start: {
					line: 0,
					character: 1,
				},
				end: {
					line: 0,
					character: 1,
				},
			},
		},
	}			
];
```

**Comment by jrieken** [comment]
> n particular, typing "it" only gives a completion for "insertText" instead of "item" and "insertText".

That's expected when appending only `tem` and `nsertText`. The reason being is that the `t` (the `i` isn't considered) as the first prefix character must match "strong", e.g an upper case or post-separator character.

**Comment by jrieken** [comment]
> Yes, that seems to be related. I patched gopls to overwrite the "i" instead of appending to it and the completion works as expected.

I would then strongly advise to use this approach - mentally user think of the word(-part) they have typed and that want that to be matched/highlight. E.g the `i` should be highlighted when showing `item` and `insertText`

**Comment by myitcv** [comment]
Joining this conversation a little late. The question I have is how the editor (Vim in my case) is supposed to know where the completion starts. Because now the FilterText and TextEdit both contain the untrimmed content, is the editor expected to calculate where this completion starts?

**Comment by myitcv** [comment]
Apologies, I totally missed that this information is of course in the Range of the TextEdit. Apologies for the noise.
