### ISSUE TITLE
cursor jumps after edits have been applied

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-languageserver-node#493]
In certain cases with [`gopls`](https://golang.org/x/tools/cmd/gopls), we have to return a full file edit when we format a file. The reasoning behind this is handling of line endings - the `gofmt` command in Go only ever returns LF line endings, so for users with CRLF endings, we return a full file with entirely new contents.

However, when those edits get applied, it seems that VSCode does not attempt to replace the cursor at its original position - it just jumps to the beginning of the file. Is there any way to avoid this issue? Some additional context can be found here: https://github.com/golang/go/issues/31937.

Thank you!

**Comment by dbaeumer** [comment]
The problem is indeed the single edit which gives the editor little glue on where to preserve the cursor. Usually the editor tries to adjust the cursor in the range of the edit that contains the cursor which in your case is the full file.

Using single edits is in addition bad since it will for example make it hard to preserve things like break points as well.

I am not understanding why you need to use a full edit when the line ending is `CRLF`. The only case I see is when the file is in `LF` and the formatter wants to change it to `CRLF`. But even this can be done using edits. An edit that spawn from the last character on line n to the first character (0) on line n+1 capture the line ending without needing to know what type of line ending is used.
