### ISSUE TITLE
onDidChangeContent receiving files outside of current workspace

### ISSUE THREAD

**Issue by antross** [microsoft/vscode-languageserver-node#506]
Originally reported to the webhint project via https://github.com/webhintio/hint/issues/2747

To repro:
* Install the webhint VS Code extension (1.0.5)
* Install the TSLint VS Code extension  (1.2.2)
* Open a `tsconfig.json` file

Result:
Files from the TSLint extension are analyzed by the webhint extension even though they are not part of the current workspace:
![image](https://user-images.githubusercontent.com/785009/62063909-6e766b80-b1f1-11e9-9c04-2a6662eb23da.png)

Debugging revealed that `onDidChangeContent` fires in the language server for `~/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.2/schemas/tsconfig.schema.json` when the local `tsconfig.json` is opened.

It's not clear to me whether this is truly an issue with `vscode-language-server` or is somehow caused by interaction with the TSLint extension, but filing here initially given I find it surprising that `onDidChangeContent` can ever return files from other installed extensions.

**Comment by dbaeumer** [comment]
Since editors can open files outside the workspace (VS Code doe have support for this and even support multiple folders) the document URIs are not restricted to files inside the workspace folder. As soon as the file gets opened in the editor (being it programatically or by user interaction) the VS Code API fires a corresponding event which is forwarded to the server.

So things like this need to be handled by the extension / server.

I will close the issue. Please ping if you think otherwise.

**Comment by antross** [comment]
I would agree if this file had been open in the editor, but it was not.

Somehow this file is getting passed to the webhint extension from the TSLint extension without actually being in the workspace or being open in the editor. Perhaps there's something the TSLint extension is calling that triggers this, but it doesn't result in a user-visible document being opened.

**Comment by dbaeumer** [comment]
@antross the open event is although fired if the document is opened programatically in a buffer since the editor claims ownership of the document (the server is not allowed to touch the content anymore). It might even change it. So I guess that the extension for some reason loads that file into a document buffer on the extension host side. For LSP there is technically no difference between a visible document and a non visible document.

**Comment by antross** [comment]
> For LSP there is technically no difference between a visible document and a non visible document.

@dbaeumer Thanks for the clarification. Don't suppose there's a way an extension could tell the difference is there? Possibly by checking with the client portion of the extension?

**Comment by dbaeumer** [comment]
There are discussion if we had a intent however it is hard to make sure that we always know the intent. An extension could open a document first in a buffer and then in the editor. If we add an intent we would need to close and reopen in LSP since the intent changes. So I would like to stay away from this.
