### ISSUE TITLE
Can I rely on didChangeConfiguration to be always called after server initialization?

### ISSUE THREAD

**Issue by henryju** [microsoft/vscode-languageserver-node#524]
Hi,

Looking at the startup sequence of my LS under VSCode, I noticed that the didChangeConfiguration notification seems to be always sent before the first didOpen. I had the idea to rely on that to get the initial values of my extension settings (to avoid passing them as initialize params, or doing an extra configuration request). But then I realized this behavior doesn't seem to be specified in the LSP. Is it intentional? Can I rely on it? Will it be future proof?

```
[Trace - 15:17:14] Sending request 'initialize - (0)'.
[Trace - 15:17:23] Sending notification 'initialized'.
[Trace - 15:17:23] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 15:17:23] Sending notification 'textDocument/didOpen'.
```

**Comment by dbaeumer** [comment]
No, you can not rely on this since it is not speced that way. In general you should rely on the new way to getting configuration by using the `workspace/configuration` request that is sent from the server to the client. See https://microsoft.github.io/language-server-protocol/specification#workspace_configuration.
