### ISSUE TITLE
IncrementalTextDocument.getText performance issue

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-languageserver-node#527]
`IncrementalTextDocument.getText` is much slower than `FullTextDocument.getText`

Unfortunately, there's existing code that calls TextDocument.getText in loops. TextDocument.getText is the only API to get the content of a TextDocument and it was never specified that this is a potentially expensive operation.

The fix is probably to have IncrementalTextDocument.getText remember the string instead of recomputing it every time.

**Comment by dbaeumer** [comment]
@rebornix can you have a look. This would need to be fixed may be in `vscode-textbuffer`

**Comment by rebornix** [comment]
Traversing the tree is cheap but concatenating the str and then flattening it is costly. But I agree that this should be fixed in `vscode-textbuffer` as library users don't necessarily need to know about the implementation details.

@Jma353 it seems you are still interested in this one so feel free to send a pr to https://github.com/microsoft/vscode-textbuffer. The only thing to note is the lifecycle of the cached string, as we don't want to hold references to them forever

* we are going to add versioning to text buffer, which can be a simple digit and private.
* cache the latest result and de-ref when the version increments.

@aeschli it would be great if you can provide some guidance on how to run some real world  benchmarks, especially the ones in which you run into the perf issue.

**Comment by dbaeumer** [comment]
@aeschli and I had a long disucssion about this. Our finding are:

- there is not a single best incremental text document implementation
- the implementation mostly depends on the scanner that is used afterwards. If the scanner for example uses a streaming API the text document best exposes something like a character sequence.

So we decided to move forward as follows:

- refactor the server code to make a TextDocuments generic so that users can bring their own text document implementation.
- remove the dependency to microsoft/vscode-textbuffer

Let server implementors decide which incremental text buffer implementation they want to use. One will be piece tree implementation.

Since we never had the incremental text document in a NON next version this will not be a breaking change.

**Comment by rebornix** [comment]
It sounds right to me. The way of reading text buffer can be only optimized based on what the scanner asks for and the detailed implementation of the buffer.

`vscode-textbuffer` can be used as an example how another text buffer implementation can be hooked into lsp-node in samples or readme.

**Comment by dbaeumer** [comment]
I will close the issue. The server side has no a pluggable text document story so developers can choose which one to use depending on their requirements.
