### ISSUE TITLE
TS2339: Property 'range' does not exist on type 'TextDocumentContentChangeEvent'

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode-languageserver-node#563]
I updated my server's dependency from `^5.1.0` to `^6.1.0`. As a part of 72788f857758cacfe6eb9356a8cacca3aef288fc and c7216c9df48786cf2e04cc2dd669a13a14cc42ad, `TextDocumentContentChangeEvent` was changed. Instead of `{ range, rangeLength?, text }` it became a `{ range, rangeLength?, text } | { text }`. This `|` is causing errors in my server with reports of TS2339 as I reference `range` directly with `changes[i].range`.

From googling my options seems to be to use `as any` or access with a key like `['range']`. Is there any other way around this? I'm hoping it's just due to me not fully grasping some TypeScript concept...?

**Comment by dbaeumer** [comment]
The problem is that range before was declared as `range?: Range` which in strict mode should have already created a compile error in the past since you didn't handle the case correctly. But may be you didn't compile in strict mode. We have some helper methods to determine the type. They are:

```
	private static isIncremental(event: TextDocumentContentChangeEvent): event is { range: Range; rangeLength?: number; text: string; } {
		let candidate: { range: Range; rangeLength?: number; text: string; } = event as any;
		return candidate !== undefined && candidate !== null &&
			typeof candidate.text === 'string' && candidate.range !== undefined &&
			(candidate.rangeLength === undefined || typeof candidate.rangeLength === 'number');
	}

	private static isFull(event: TextDocumentContentChangeEvent): event is { text: string; } {
		let candidate: { range?: Range; rangeLength?: number; text: string; } = event as any;
		return candidate !== undefined && candidate !== null &&
			typeof candidate.text === 'string' && candidate.range === undefined && candidate.rangeLength === undefined;
	}
```

to check what event you have received. But they are not public. Are you using TextDocuments on the server. If so you might want to look at the new text documents npm package which now supports increment updates as well.

**Comment by rcjsuen** [comment]
> The problem is that range before was declared as `range?: Range` which in strict mode should have already created a compile error in the past since you didn't handle the case correctly.

I handled it by checking if the member exists. I guess this was not the right way to do it?

```
if (!changes[i].range && !changes[i].rangeLength) {
```

> But may be you didn't compile in strict mode.

I don't have that setup in my `tsconfig.json` so perhaps that is why.

> We have some helper methods to determine the type. They are:
> 
> ```
> 	private static isIncremental(event: TextDocumentContentChangeEvent): event is { range: Range; rangeLength?: number; text: string; } {
> 		let candidate: { range: Range; rangeLength?: number; text: string; } = event as any;
> 		return candidate !== undefined && candidate !== null &&
> 			typeof candidate.text === 'string' && candidate.range !== undefined &&
> 			(candidate.rangeLength === undefined || typeof candidate.rangeLength === 'number');
> 	}
> 
> 	private static isFull(event: TextDocumentContentChangeEvent): event is { text: string; } {
> 		let candidate: { range?: Range; rangeLength?: number; text: string; } = event as any;
> 		return candidate !== undefined && candidate !== null &&
> 			typeof candidate.text === 'string' && candidate.range === undefined && candidate.rangeLength === undefined;
> 	}
> ```
> 
> to check what event you have received. But they are not public.

Would be helpful if they were public. Though I see they are also in this other npm package. :P

> Are you using TextDocuments on the server. If so you might want to look at the new text documents npm package which now supports increment updates as well.

I am handling the incremental changes myself so no, I wasn't using `TextDocuments` on the server.

**Comment by dbaeumer** [comment]
I will keep the issue open then to provide the methods as public API.

**Comment by rcjsuen** [comment]
@dbaeumer Thank you for accommodating.

Please expose it in the `vscode-languageserver-protocol` package so that you don't have to declare a dependency on `vscode-languageserver-textdocument`.

**Comment by dbaeumer** [comment]
Makes sense.

**Comment by mattacosta** [comment]
Just hit this myself when upgrading to `6.1.0`.

I'd like to note that there's no strict mode issue here either. Given the previous type definition, our handling was correct. What used to be `{ range, text } | { range, rangeLength, text }` is now `{ text } | { range, text } | { range, rangeLength, text }`. TypeScript correctly* narrows to the first case in each instance, and since `range` doesn't exist anymore, you get an error.

Technically, this is also a grey area in terms of backward compatibility. One the one hand, you've removed a property from a base type (or at least something shaped like a base type from TypeScript's point of view), but on the other, there is no explicit relationship between the types.

**Comment by dbaeumer** [comment]
There is no behavioral breakage in terms of the LSP specification. That one clearly said:

> If range and rangeLength are omitted the new text is considered to be the full content of the document.

However it was typed in a bad way in the past since you were able to send a event where text and rangeLength was set. I agree that the typing is breaking which I usually try to express by moving the server and client versions to a new major version number.

**Comment by dbaeumer** [comment]
Protocol now exports a `TextDocumentContentChangeEvent` namespace with the two functions.
