### ISSUE TITLE
Converter.asCompletionItem doesn't handle insert/replace

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode-languageserver-node#586]
The implementation of `asCompletionItem` contains this explicit check:
```
if (isInsertReplace(value)) {
    throw new Error(`Receving unknown insert replace range.`);
}
```
which will fail if the range is specified with the `inserting` and `replacing` properties as they're not part of the LSP yet. See [here](https://github.com/microsoft/language-server-protocol/issues/846).

However, VS Code is now returning completion items with ranges in this format (e.g. when calling `vscode.commands.executeCommand<vscode.CompletionList>('vscode.executeCompletionItemProvider', uri, position, context)`). 

My understanding is that if I pass a valid `code.CompletionItem` to `Converter.asCompletionItem`, I should get back a valid  `proto.CompletionItem`. However, in this case it throws.

Please let me know if I'm misunderstanding how `Converter` is intended to be used.

**Comment by jrieken** [comment]
Yeah - that is correct. With the new insert/replace API those commands now return different information

**Comment by dbaeumer** [comment]
> My understanding is that if I pass a valid code.CompletionItem to Converter.asCompletionItem, I should get back a valid proto.CompletionItem. However, in this case it throws.

This is only true for items that came from the LSP server. Since the LSP server can't create an item with insert / replace edits (it is not supported) we don't support converting VS Code completion items into insert /replace. As said major reason is that there in no support for that yet (I have coded it up but it will be release as a next version since it requires and official spec change).

The only workaround I can think of is to do the following: if the VS Code completion item has both ranges convert it back into one only having the insert range and send that over the wire.

**Comment by dbaeumer** [comment]
@daytonellwanger whether or not a completion item should have a insert/replace range when sent over LiveShare should depend on the capability the client supports. Even if a VS Code completion Item has both ranges you can't send it to a VS Client since a VS client has currently no support for it. This is why the specification will add a capability whether a client has support for this or not (see https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/encodingSupport/protocol/src/protocol.ts#L1531)

**Comment by dbaeumer** [comment]
@daytonellwanger is it OK for you to close the issue?

**Comment by daytonellwanger** [comment]
Thanks for the clarification, Dirk!
