### ISSUE TITLE
Insert replace adoption is painful

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-languageserver-node#600]
Testing https://github.com/microsoft/vscode/issues/93754

I tried to adopt 6.2.0-next.1 in the JSON language server and it turned out to be quite painful

- CompletionItem is no longer compatible to the previous version as the type of `textEdit` has changed
- (a) Passing a CompletionItem to `resolveCompletionItem` of the old, not-yet adopted version of the JSON language service doesn't compile
- (b) If I update the `json-language-service` with the new API, I break old, not-yet adopted users.

Ideally the change would be a new optional property. 
I would suggest `CompletionItem.insertReplaceTextEdit`

**Comment by dbaeumer** [comment]
The change is compatible inside the protocol itself. I do see that this is breaking on the level of the API when a diagnostic flows back even if no adoption has been done. 

Instead of adding another property, which IMO makes things more confusing, I am in favor of simple raising the version number to 7.0.0 as we always do when these changes happen.

**Comment by aeschli** [comment]
A new version would be correct, but will ripple through my server and services. All that just for a small feature.
Why not `CompletionItem.insertReplaceTextEdit` or `CompletionItem.textEdit2` ? 
It's also possible to do this:
CompletionItem.textEdit? : TextEdit | CompletionItemTextEdit;
CompletionItemTextEdit {
    newText: string, range: Range, insertRange?: Range, replaceRange?: Range
}
CompletionItemTextEdit is compatible with TextEdit (range needs to stay and is duplicate info)

That way I can have my service work with old and new clients.

**Comment by dbaeumer** [comment]
But I basically raise the major client / server version number with every protocol version. So I don't think that this is much different than moving from 3.14 to 3.15. The new feature can't go into a 3.15.x protocol version anyways. It will go with all the other new feature (like call hierarchy or semantic coloring) in version 3.16

I am not a fan of  `CompletionItem.insertReplaceTextEdit` nor `CompletionItem.textEdit2`. And `InsertReplaceTextEdit` in its current form has the disadvantage that someone can create an edit with `range`, `insertRange` and `replaceRange`. 

One possibility would be 

```ts
InsertReplaceTextEdit {
    newText: string, range: Range, replaceRange?: range
}
```

But I am not sure if this makes things easier or harder to understand since we need to write more documentation around it.

**Comment by aeschli** [comment]
Given this is a breaking API change, doesn't that mean the types version would have to go to 4.0?

```
InsertReplaceTextEdit {
    newText: string, range: Range, insertRange?: Range, replaceRange?: Range
}
```
we define that range is what the LS thinks should be the preferred range for the currrent proposal.
Depending on the situation, that can be equal to the `insertRange` or the `replaceRange`.

VSCode has a setting that says whether insert or replace is the default, so it will just use `insertRange`  or `replaceRange` if present and ignore the default range. If `insertRange` and  `replaceRange` are not set, it can fall back to the default range.

I think that's equally complicated than the proposed InsertReplaceTextEdit.

I personally have not used insert/replace with proposals unless in testing. It's IMO a small feature that I would rather skip than start a version ripple, which is a big hassle for every LSP API client.

**Comment by dbaeumer** [comment]
> Given this is a breaking API change, doesn't that mean the types version would have to go to 4.0

Yes, but after discussion around this I decided to version `types` & `protocol` using the LSP version number and signal any breakage through the LSP client and LSP server. The `types` and `protocol` package is hardly used outside of the two.

I have requests from other languages that would like to adopt the insert / replace feature. So IMO we shouldn't skip this. And as said it will got into 3.16 with a lot of other features which very likely will require increasing the version number to `7.x` for the client and server anyways.

> VSCode has a setting that says whether insert or replace is the default, so it will just use insertRange or replaceRange if present and ignore the default range. If insertRange and replaceRange are not set, it can fall back to the default range.

Good point. But brings us back to square one :-). Do we type things correctly or backwards compatible.

**Comment by dbaeumer** [comment]
@aeschli is this still an issue for you. I am not very keen on changing this now.

**Comment by aeschli** [comment]
In the meantime I adopted all my language services (I had no choice).

**Comment by dbaeumer** [comment]
Thanks!! I changed the diagnostic code though to make it non breaking
