### ISSUE TITLE
Diagnostic.code is breaking clients

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-languageserver-node#601]
Testing microsoft/vscode#93754

the type change of Diagnostic.code is breaking for libraries that take a Diagnostic as parameter, e.g. as part of the `CodeActionContext`.

Why is part of the code and not a new property on the diagnostic? 
The documentation says `A target URI to open with more information about the diagnostic error.`

- does not sound that this is code specific, but a link for the given diagnostic
- i find `target` not to be a helpful property name
- 'error' is also not correct here, the diagnostic can also be a hint, info or warning 

Suggestions:

`Diagnostic.codeHyperlink`
or
`Diagnostic.codeDescription of type { href?: URI } ` allowing future additions

**Comment by dbaeumer** [comment]
@aeschli: good catch. 

@jrieken: are we ignoring this in VS Code?

**Comment by jrieken** [comment]
Yes - for VS Code we ignore these "flow-back-breakages". Btw this *does* happen with completion items: all consumers of the API commands, prominently LiveShare and Razor, are affected by this.  

We considered things like `codeLink` etc but decided against them because they give no guidance, e.g we wanted to make this an explicit link for the error code, not just a link. However, will still have on our plans to support (mini?)markdown descriptions, which will then have support for arbitrary links. That said, something like `codeDescription` will be awkwardly in-between those.

@aeschli Is this a real problem or theoretically. At least in vscode.d.ts , the `code` property was already an or-type (string | number) and I think adding another case is relatively easy

**Comment by aeschli** [comment]
Or-types are not a problem in general. The problem is that the change is an API breakage as Diagnostics are not just returned by providers but also an argument to code actions.

I use CodeActionContext here: https://github.com/microsoft/vscode-css-languageservice/blob/460bab34b4ef23985ee734ebf3fc4f3250285b1f/src/cssLanguageService.ts#L52

(this not vscode.d.ts, but LSP's vscode-languageserver-types)

new CodeActionContexts can no longer be assigned to old CodeActionContexts

-> I need to adopt, increase the major version, rippling down API client to do the same.

IMO the feature is too small to justify that work.

**Comment by dbaeumer** [comment]
I looked into this again and since we have clients and server I agree with @aeschli that we should not break this since there might be clients using a server which they don't have source code control of.

So I will go with the `codeDescription` approach. @jrieken do you see any problems with this?
