### ISSUE TITLE
json-rpc: MessageConnection.Dispose should close the streams

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vscode-languageserver-node#62]
Given a `MessageConnection` is initialized with streams, and at least the read stream is pretty much useless after calling `MessageConnection.listen()` since buffering could have consumed an undefined number of bytes from the stream, `MessageConnection.dispose()` should call `close()` on the streams.

**Comment by dbaeumer** [comment]
To my knowledge there is no documented way in node to close a readable stream. Given that the connection actually doesn't own the streams I argue that it shouldn't close them either. I do see the argument that the readable stream is not valid anymore. To ease things would it help to have a event fired when the connection gets disposed so that clients can react?

**Comment by AArnott** [comment]
A disposal event would allow us to fix it on our side, yes.
We're using a readable-writable stream (it's a pipe, internally), so the `end()` method on the writable effectively closes the whole thing.

**Comment by dbaeumer** [comment]
OK. Will look into it then.

**Comment by dbaeumer** [comment]
Fixed by providing and event.

**Comment by AArnott** [comment]
Thank you!
