### ISSUE TITLE
Provide a way to request start signature help from server

### ISSUE THREAD

**Issue by heejaechang** [microsoft/vscode-languageserver-node#663]
we have a scenario where we would like to have signature help dynamically started but it is not based on a trigger char. can LSP add support to request signature help at the current position from a server like how the server can request a progress bar?

an example scenario is that, if a user commits a method from completion, we would like to insert methodName + () and put the caret between () and start signature help.

**Comment by rcjsuen** [comment]
> we have a scenario where we would like to have signature help dynamically started but it is not based on a trigger char. can LSP add support to request signature help at the current position from a server like how the server can request a progress bar?

@heejaechang You mention the LSP here. Are you asking for something to be added or changed to the specification or are you asking for some API from VS Code's LSP client library?

> an example scenario is that, if a user commits a method from completion, we would like to insert methodName + () and put the caret between () and start signature help.

Requests about this particular scenario has been raised in the past. I found a few of these issues but I wouldn't be surprised if there are more:

- https://github.com/microsoft/vscode-languageserver-node/issues/376
- https://github.com/microsoft/vscode-languageserver-node/issues/471
- https://github.com/microsoft/language-server-protocol/issues/523

**Comment by dbaeumer** [comment]
@heejaechang if you want to programmatically trigger signature help at a cursor location you can use the command `editor.action.triggerParameterHints`. This is of course VS Code specific 

If we want to add something like this to the spec then we have to start in the language server repository :-). And I am actually not a fan of allow servers to trigger UI interaction via LSP.

**Comment by heejaechang** [comment]
Hi. I meant adding new feature in spec. (sorry, I thought this is the lsp repository).

we know about "editor.action.triggerParameterHints" trick (GO LS was using it), but we need to support VS as well with same server, so it would be nice if it is not client specific.

"And I am actually not a fan of allow servers to trigger UI interaction via LSP."
we are fine with new option in completion if you want it to be more declarative rather than imperative like server asking signature help at random point.

**Comment by jakebailey** [comment]
Another problem is that we already use commands for other things, including running a command based on completion items (VS Code calls the LS again). In order to send multiple commands, we could write an extra handler to reissue the commands in VSC, but it would be VSC specific.

I'm not sure what the right method is here, but given the specification of signature help (you need to type a specific character to trigger it, like parens and commas) and the proliferation of snippet-based completions for functions to add parens/placeholders which are designed to avoid typing parens and commas, I'd hope for a way to do this cleanly.

Would it make sense for VSC to always ask for signature help on acceptance of a function/method (eliminating the hack used by vscode-go among other things), or is it too weird to so generically trust the `kind` returned by an LS?

**Comment by dbaeumer** [comment]
If we want to have this in the spec the right approach is to add this to a completion item. The interesting question is how to spec this (e.g. using a position?). As said I am against allow the server to open UI since the user could have already typed or moved the cursor.

**Comment by rcjsuen** [comment]
> If we want to have this in the spec the right approach is to add this to a completion item. The interesting question is how to spec this (e.g. using a position?).

@dbaeumer Would a naive solution like https://github.com/microsoft/vscode-languageserver-node/issues/471#issuecomment-482628859 work? What do you want to use a position for?

**Comment by dbaeumer** [comment]
Yes, but only if the signature help is to be trigger at the cursor location.

**Comment by rcjsuen** [comment]
> Yes, but only if the signature help is to be trigger at the cursor location.

@dbaeumer I find it unlikely that I would want automatic signature help triggered at some location that may not be applicable to my current cursor location. What use case are you thinking of?

**Comment by heejaechang** [comment]
I like https://github.com/microsoft/vscode-languageserver-node/issues/471#issuecomment-482628859. simple and straightforward. if we worry about extending it in the future, the triggerSignatureHelp could be an option object rather than simple boolean?

**Comment by rcjsuen** [comment]
> Hi. I meant adding new feature in spec. (sorry, I thought this is the lsp repository).

@heejaechang Since this was your original intent, can you open a new issue in the [microsoft/language-server-protocol repository](https://github.com/microsoft/language-server-protocol/) to ensure that the wider community can provide feedback about this request? I know https://github.com/microsoft/language-server-protocol/issues/523 exists but it's been closed so...

**Comment by dbaeumer** [comment]
I agree. We need to start this in the LSP repository.
