### ISSUE TITLE
Throwing exceptions that reach the api seem to cause content-length errors

### ISSUE THREAD

**Issue by Razzeee** [microsoft/vscode-languageserver-node#676]
So we recently rewrote a part of our language server and that resulted in the fact, that exceptions could reach the edge of our system. VSCode seems to be fine with this, as it seems to ignore these messages, but editors like VIM are not happy when this happens.

See the referenced issue:
https://github.com/elm-tooling/elm-language-server/issues/337

I'm not sure what best to do about this, if we could have better default, we just need to make sure that exceptions never reach the api or if this is just something that should be documented.

**Comment by dbaeumer** [comment]
@Razzeee are you talking about the server side?

**Comment by Razzeee** [comment]
Yes, correct. Should be fixed on the server side.

**Comment by dbaeumer** [comment]
Two things: in the next version of the library this will not be an exception anymore. It will be reported as an error event. This being said there might still be cases where an exception can reach the event loop. If a node server wants to protect against this it should use `process.on('uncaughtException', () => { .... })`.

I will close the issue since there is IMO no further work to do.
