### ISSUE TITLE
IPCMessageWriter and IPCMessageWriter not available anymore

### ISSUE THREAD

**Issue by carmenberndt** [microsoft/vscode-languageserver-node#709]
With the new version `vscode-languageserver` v7, both `IPCMessageWriter` and `IPCMessageReader` aren't available anymore. This is needed to create a connection over `process.stdin` and `process.stdout`. What's the workflow to do this with the new version?

**Comment by dbaeumer** [comment]
@carmenberndt this is a breaking change caused by the split into common, node and browser. As document in the Readme (https://github.com/microsoft/vscode-languageserver-node/blob/master/README.md) you now need to import node specific API separately. The default import only imports the common API. The `IPCMessageWriter` and `IPCMessageWriter` are in `vscode-jsonrpc\node` or `'vscode-languageserver/node'` if you develop a server.
