### ISSUE TITLE
Client error `Failed to determine file type`

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode-languageserver-node#734]
1. Server registers feature of `workspace/didDeleteFiles`.
2. The register option must contains property `FileOperationPattern.matches`.
3. Delete a file.
4. The client reports error `Failed to determine file type for xxxx`

**Comment by dbaeumer** [comment]
@sumneko can you provide me with a GitHub repository I can clone that demos this. This doesn't happen for me with a local file system.

**Comment by sumneko** [comment]
Heres you are: https://github.com/sumneko/sample-1

This is my OS information
版本: 1.53.0-insider (user setup)
提交: 565dc9704f27619ad73867fddde6bbca88110c18
日期: 2021-02-01T16:49:24.403Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

This is what I found, when deleting a file, client calls `await FileOperationFeature.getFileType(uri)`, which causes a `FileNotFound` error.
![client-error](https://user-images.githubusercontent.com/5213431/106581140-7ef16a00-657d-11eb-88ea-db23785aad7b.gif)

**Comment by dbaeumer** [comment]
Thanks for the repository. That is a good catch. Let me see how to fix this.

**Comment by dbaeumer** [comment]
@DanTup actually we do have a problem here. In the delete case we can't ask the file system provider whether the URI maps to a file or folder since it is basically gone. To fix this we would need to do the following: capture the type in the will delete phase and use it in the didDelete phase. Can you work on fixing this?

**Comment by DanTup** [comment]
@dbaeumer right now this code fires for all of the tests, because the call to `stat` fails because the files don't really exist on disk. Is there a way we could make this code work the same as when running for real? Is it reasonable to actually create the test files on disk in a temp folder or something?

**Comment by DanTup** [comment]
@dbaeumer I have a potential fix here:

https://github.com/microsoft/vscode-languageserver-node/compare/master...DanTup:fix-delete-file-type

I'm not sure if it's the right approach.

But I'm also wondering:

- What about onWillCreate?
- Should onDidRename be using `newUri` instead of `oldUri`?

(I might not be able to get back to this for a few days, so if this is urgent please feel free to make changes to my branch).

**Comment by dbaeumer** [comment]
@DanTup for the tests: we should install out own file system provider for the tests which implements the stat call and things would then work as expected in the tests.


We can not address this for `onWillCreate` since we don't know what is going to be created. So we should document that when describing the filter.

I would leave `onDidRename` on the oldUri

**Comment by DanTup** [comment]
> we should install out own file system provider for the tests which implements the stat call and things would then work as expected in the tests

Can we install one for `file://` or would we need to use a different scheme?

> I would leave `onDidRename` on the `oldUri`

But `oldUri` will no longer exist on disk once `onDidRename` has fired, so it will fail?

**Comment by dbaeumer** [comment]
> Can we install one for file:// or would we need to use a different scheme?

No, I would create an own scheme.

> But oldUri will no longer exist on disk once onDidRename has fired, so it will fail?

Agree but we can do the same onWill trick. It does IMO make more sense to filter against oldUri.

**Comment by DanTup** [comment]
@dbaeumer Sorry for the delay - I believe I have this working (and tested) now:

https://github.com/microsoft/vscode-languageserver-node/pull/744

I'm not sure how to modify the spec about `onWillCreate`. It actually feels a bit weird to say "onWillCreate's file/folder filter type will be ignored because at the time the event fires, it's not known whether the item is a file or folder" because this seems to be entirely a limitation of VS Code's API. There's no reason other editors/LSP Clients would not be able to handle this correctly. Perhaps it's better unspec'd, and VS Code's event updated to include this (this could also be extended to the others, and short-cut the `stat`ing when available)?
