### ISSUE TITLE
textDocument/references and textDocument/implementation occasionally opens files

### ISSUE THREAD

**Issue by njames93** [microsoft/vscode-languageserver-node#738]
When performing a Find all references or implementations on a symbol, If references/implementations are found in other files, occasionally in the results page it will sort of open the file.

By that I mean the client will send a `textDocument/didOpen` request to the server, but the file won't actually show up in vscode open editors, Once this happens there's no trivial way to client to to send a `textDocument/didClose` request to the server. Opening the file and closing it again doesn't have this effect, neither does clicking the little x to dismiss it
![image](https://user-images.githubusercontent.com/5469473/106932597-d58ead80-670f-11eb-8983-8c03cb038140.png)

The main issue with this is with diagnostics. Once a file is 'open', the server will happily start to send diagnostics for that file even though it's one you aren't working on, and possibly don't have control over. It them wont clear them until either you fix them, which can sometimes not be possible or desirable(style violations where fixing them is a headache for version control), or the client decides to send the didClose request, which is where the issue lies.

For reference I'm using clangd with the vscode-clangd extension and vscode version 1.52.1.
I'm not entirely sure where this behaviour is introduced, although I doubt it's the vscode-clangd extension as that doesn't do any special handling with these requests. I'd guess this behaviour is coming from the LanguageClient interface which is why I filed it here, feel free to move this if that's not the case.

**Comment by dbaeumer** [comment]
The open event is not a visual open event in LSP. It is a transferal of content ownership from the server to the client. So whenever the client reads the content of a file it needs to open it since a server is not allowed to read that content of that files from disk anymore.

I do see the problem of a server not knowing that it doesn't need to compute diagnostics for these files if it doesn't operate in a workspace diagnostic mode. We try to address this with this proposal: https://github.com/microsoft/vscode/issues/112501

**Comment by dbaeumer** [comment]
I will close this issue as a dup of the pull model.
