### ISSUE TITLE
How to leverage the ParameterStructures field in RequestType

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-languageserver-node#762]
Noticed that in the constructor of `RequestType` we can specify the `ParameterStructures` field, but I have a question about how to use that field.

Let's say I have a requestType defined as

```ts
export const type = new RequestType<boolean, ReturnType, void>('method', ParameterStructures.byName);
```

From my understanding, the code [here](https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/client.ts#L177): 

```ts
sendRequest: <R>(type: string | MessageSignature, ...params: any[]): Promise<R> => connection.sendRequest(Is.string(type) ? type : type.method, ...params),
```

ensures that the first param is a string,

Then in the implementation [here](https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/connection.ts#L1200-L1236), it will not fall into the else block, and the `ParameterStructures` will be `auto` without checking the field set in the request type.

Is there anything I missed?

**Comment by dbaeumer** [comment]
@jdneo you might want to have a look at the tests here: https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/node/test/connection.test.ts#L74

Params by name are in JS always passes as a literal. That doesn't mean that the first param is the name and the second the value. 

In general you shouldn't care about this in LSP since LSP always uses a literal param object. LSP has no support for example for positional params. It is in the jsonrpc library to be conformant with the JSON RPC spec (https://www.jsonrpc.org/specification#parameter_structures)

**Comment by jdneo** [comment]
Thank you @dbaeumer  I'm actually wondering when will the code fall into this else block: https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/connection.ts#L1231-L1235

Because the invocation here seems to make sure the type will be passed as a string:

```
sendRequest: <R>(type: string | MessageSignature, ...params: any[]): Promise<R> => connection.sendRequest(Is.string(type) ? type : type.method, ...params),
```
