### ISSUE TITLE
Trigger character ':' not working for YAML language completions

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-languageserver-node#765]
Hello,
We are from the Azure ML Extension team. We are creating an Azure ML Language server for Azure ML YAML config file completions and other language features on top of RedHat yaml-language-server. We are setting trigger character as ':' in our language server. 

E.g. 
![image](https://user-images.githubusercontent.com/44413557/117852849-647a0b80-b2a5-11eb-9d2f-c279213f3bf4.png)

But, when I type ':' after any YAML key (e.g. target), the completions are not shown. After debugging the language server, we found out that the completion methods are called properly and correct completions are returned.

But, when we set the trigger character as ' '(space), it works properly, so hitting space after ':' gives correct completions.

Here's the word pattern that redhat defines in their language configuration file:
![image](https://user-images.githubusercontent.com/44413557/117853405-026dd600-b2a6-11eb-8efd-7192c98c5b24.png)
which we inherit in our LS

**Comment by dbaeumer** [comment]
How do the completion items look like. I am pretty sure they get filtered in VS Code itself due to the fact that they don't match the prefix of the word you are typing.

You can check this by debugging the client side and see if the items are correctly handed back to the VS Code API here: https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/client.ts#L1629

**Comment by shsuman** [comment]
This can be closed now because it seems it is an issue on our part. I tested with some test completion items and they are working fine.

**Comment by dbaeumer** [comment]
OK. Great. Thanks for getting back to me.
