### ISSUE TITLE
How to trigger client-initiated progress for document formatting

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vscode-languageserver-node#793]
Does VS Code (and its LanguageClient) support client-initiated progress for a document formatting request? (If not, could/should it?)

I have a server that advertises supporting work done progress in its [registration](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_formatting), but I'm unable to get the client to include a workDoneToken in the request.

**Comment by davidmatson** [comment]
And similarly, is there a way I can get the VS Code UI to show a Cancel button for a document formatting request? I'd like to test the server-side behavior when the client sends [cancel](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#cancelRequest) for the formatting request, but I can't figure out how to get VS Code to trigger a cancellation in this case.

**Comment by davidmatson** [comment]
I was able to trigger Cancel by switching documents while the formatting request was in progress. I have found no way to trigger client-initiated progress though, even when the client/registerCapability request for textDocument/formatting has "workDoneProgress": true in registerOptions.

**Comment by dbaeumer** [comment]
@davidmatson VS Code doesn't support client initiated progress for formatting not for most of the user language based requests. Unless it does there is little that the LSP libraries can do to make this happen. I will therefore close the issue. This can enabled when VS Code support progress for language provider requests.

Please note that LSP supports this since other editors do have client initiated progress for their language features.
