### ISSUE TITLE
Compatibility with older versions of vscode

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode-languageserver-node#839]
When I upgraded to "vscode-languageserver-protocol": "^3.17.0-next", and "vscode-languageclient": "^8.0.0-next", some folks reported problems on older versions of vs code.  Can you provide a definitive statement somewhere about which versions of VS code are supported by reach release of these libraries?

**Comment by dbaeumer** [comment]
You can always use an older version of the library. The reason that the current next version requires 1.61 is the fact that the library has no support for type hierarchies which got added in 1.61. If the library adapts new VS Code features it needs to move forward.

**Comment by lovettchris** [comment]
> I have currently no plans to make features selectively per version. I will therefore close the issue.

Thanks for clarifying.  Do you then plan to fix bugs in older versions, like https://github.com/microsoft/vscode-languageserver-node/issues/825, and release something like a 7.1.1 or something?

**Comment by dbaeumer** [comment]
@lovettchris  I usually do fix bugs in older versions. The problem with #825 is that it is a breaking API change and therefore can't be back ported.

@gebner good suggestion. All I could think of is adding some sort of script that takes the value from the clients engine field and paste it into the `package.json` of the extension.

The real underlying problem is that node / VS Code only checks the engine property top level and not down the dependency tree.

**Comment by davidbarsky** [comment]
Hello! I was wondering if you'd be willing to reconsider this point, but I understand that this might be challenging:

> I have currently no plans to make features selectively per version. I will therefore close the issue.

For context, my employer has an [in-house fork of VSCode](https://developers.facebook.com/blog/post/2019/11/19/facebook-microsoft-partnering-remote-development/) which tends to be 4-5 months behind the upstream version of VSCode (while I would _personally_ like to use upstream VSCode, that's not a fight that I'm willing to take on now, let alone win...). I'm trying to port latest version of [rust-lang/rust-analyzer](https://github.com/rust-lang/rust-analyzer) to our older, internal fork, but I'd like to avoid maintaining an internal fork of the Rust Analyzer extension with the older version of t _and_ I don't want to ask the rust-analyzer team (who are made up of largely volunteers!) to spend too much effort assisting me (e.g., downgrading `vscode-languageclient` to an older version. My use-case is niche). 

The immediate issue I'm running into is that we're running 1.63 and rust-analyzer requires 1.66 but the only feature that rust-analyzer makes use of are the now-stable inlay hints. However, even when I downgrade the extension's engine to 1.63, I'm receiving the error `Cannot activate rust-analyzer: The language client requires VS Code version ^1.66.0 but received version 1.63.2022042805-dev`.

Would you be willing to version some features in the client library on the version of the LSP protocol that they were introduced in? The [metamodel](https://github.dev/microsoft/vscode-languageserver-node/blob/6a33b75c3520ad66d437c33ec9fc10d49a4675b8/protocol/metaModel.schema.json#L1) appears to have encoded this information in a semantically meaningful way.

I'm not sure if it's possible to do with NPM, but an init-time negotiation at runtime between the server and the client extension for what features are supported (e.g., everything in LSP 3.16 and below, or maybe something more fine-grained?) would be _really_ helpful rather than failing-fast at extension load time. It'd also reduce the maintenance burden on the rust-analyzer volunteers. I'm willing to extend full-time engineering effort on this package to make that feature happen, for what it's worth.
