### ISSUE TITLE
RequestCancelled should not throw a CancellationError

### ISSUE THREAD

**Issue by mroch** [microsoft/vscode-languageserver-node#889]
https://github.com/microsoft/vscode-languageserver-node/blob/615bbb5ddfc47a3e79774e4c4e4b67c7ad33bf1e/client/src/common/client.ts#L4079-L4095

Why does a `RequestCancelled` `ResponseError` get converted into a `CancellationError` when the client didn't request a cancellation?

Prior to LSP 3.17, it was not specified that `RequestCancelled` is only for when the *client* requests the cancellation (this comment is new in 3.17: "The client has canceled a request and a server as detected the cancel."). Flow has been using this to reject requests when it's still initializing.

But even with 3.17, I'm not sure why it's throwing `CancellationError` for this case. I think it should rethrow the `ResponseError` -- it could return `defaultValue`, but then it's impossible for the extension to tell that the server errored.

This is a concrete problem because VS Code allows `CancellationError` to bubble up in places like the codeAction handler, which causes it to get stuck "Waiting for quick fixes..." forever: https://github.com/microsoft/vscode/blob/3c9a85367b2933b3e9900ba175ce316250e8ee60/src/vs/editor/contrib/codeAction/browser/codeAction.ts#L143

My suggestion:
```
 if (error.code === LSPErrorCodes.RequestCancelled) { 
 	if (token !== undefined && token.isCancellationRequested) { 
 		return defaultValue; 
 	} 
 } else if (error.code === LSPErrorCodes.ServerCancelled) { 
 	if (token !== undefined && token.isCancellationRequested) { 
 		return defaultValue; 
 	} else { 
 		if (error.data !== undefined) { 
 			throw new LSPCancellationError(error.data); 
 		} else { 
 			throw new CancellationError(); 
 		} 
 	} 
 } else if (error.code === LSPErrorCodes.ContentModified) { 
  ...
```

**Comment by dbaeumer** [comment]
The fact that VS Code gets stuck on a thrown `CancellationError` should be reported to VS Code. It should IMO not happen since `CancellationError` is an official concept in VS Code API. I suggest you create an issue against VS Code demoing this using a normal VS Code extension (without LSP libs) since it makes it easier to debug.

`CancellationError` in the VS Code API has the following meaning: a provider can currently not fulfil the request. So the provider (not the client) is cancelling the request and the client is ask to call the provider again. It doesn't mean that the client has cancelled the request.

Prior to 3.17 it was unclear what `RequestCancelled` means. The intention was always that it signals that the client has canceled the request and the server acknowledge the cancel. The text in https://microsoft.github.io/language-server-protocol/specifications/specification-current/#cancelRequest gave a strong hint on that. It was never intended that the server can cancel a request by itself (without the client asking for it) since in 3.16 it was not specified what a client should do when the server cancels the request.

For 3.17 we introduce the `ServerCancelled` code to make it clear that one is for the client and the other for the server.

To keep things in a best way compatible the VS Code client does the following:

- if it receives `ServerCancelled` and the client didn't cancel the request as well throw `CancellationError` to ask the client to rerun the request.
- if it receives `RequestCancelled` then normally the client should have cancelled the request and the code will return the default value (according to the best interpretation of the 3.16 spec). If the client has not canceled interpret the `RequestCancelled` as `ServerCancelled` since things weren't 100% clear in the 3.16 spec.

I do agree that we should mention the behavior change in the change log.

IMO there is nothing we should change here since it would make things worse.

**Comment by dbaeumer** [comment]
I will close the issue since there is nothing that can be done in the libs IMO. I checked that the new behavior is mentioned in the readme.
