### ISSUE TITLE
did_rename doesn't fire when only new extension matches filter

### ISSUE THREAD

**Issue by ratmice** [microsoft/vscode-languageserver-node#915]
It appears that in the case when a server has registered for the `did_rename`, and a `FileOperationRegistrationOptions`, with a `filter:"**/*.txt"`
when the client renames a file from e.g. `foo` to `foo.txt`, no `did_rename` (and for completeness no `did_create`)
event ever gets sent to the server.

**Comment by dbaeumer** [comment]
@DanTup can you please have a look and understand if this is VS Code or us in the LSP libs?

**Comment by DanTup** [comment]
@dbaeumer what is the expected behaviour?

My guess is that no rename event is sent because the file that was renamed did not match the pattern ([only oldUri is checked](https://github.com/microsoft/vscode-languageserver-node/blob/292dd0d88b6465337e42ba40ad986fdfdeb42d4d/client/src/common/fileOperations.ts#L303)). No create event is fired because a rename event in VS Code only ever maps to rename events in the LSP client.

I think sending a create event might be a little odd, perhaps a rename event should be fired if _either_ the old or new uri match the pattern?

**Comment by ratmice** [comment]
Agreed about sending a creation event, and sending rename if either old or new is naively what I had expected,
since it makes the cases when it is fired symmetric.

**Comment by DanTup** [comment]
@dbaeumer does the same thing here apply to other globs/watchers defined in the spec? for ex [`DidChangeWatchedFilesRegistrationOptions`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didChangeWatchedFilesRegistrationOptions))? Do they include renames when only the new uri matches?

I think these should probably be the same (and made explicit in the spec)?

**Comment by dbaeumer** [comment]
@DanTup good question. I will have a look.

In general, I think that the rename should only match the old URI. That is the resource that got renamed. Matching the new name should only happen on opt in, if we want to support it at all.

**Comment by dbaeumer** [comment]
Actually, the file system watcher has no support for rename since not all watchers provide these capabilities and it is hard to re-infer. So, in this case you get a delete and a create event.

For file operation events in contrast are inferred from UI actions (not file system) hence it is clear whether the user triggered a rename of a create and a delete.

I am in favor of closing the issue as works as designed since I believe that we should only fire this on the old URI and not the new.

**Comment by DanTup** [comment]
I guess it's possible for a server that really wants this to simulate it by doing `**/*.*` and then just filtering on the server if neither old/new paths are what it's interested in too?

**Comment by ratmice** [comment]
Closing I guess then, although I do feel like it is a very weird corner case, I guess `DidRename` is primarily useful then only as an optimization where there is an existing value associated with the file, and with it you may avoid recomputing it, and not as a form of tracking without the hack @DanTup mentions.

**Comment by dbaeumer** [comment]
The idea of DidRename is nor for tracking purpose. If is to fix source code in cases where the file name must match a program symbol name (like in Java).
