### ISSUE TITLE
[Question] `workspace/applyEdit` with document changes or text changes to non-opened files

### ISSUE THREAD

**Issue by BoykoAlex** [microsoft/vscode-languageserver-node#919]
How is [workspace/applyEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_applyEdit) request affects non-opened files? For example in VSCode i see that document changes from `WorkspaceEdit` are applied to a document opened by the currently active editor. Document changes to files that are either not opened or not in active editors are not applied... although the response to the request doesn't mention any of the changes not applied.

**Comment by dbaeumer** [comment]
@BoykoAlex can you provide me with an example demoing this as a GitHub repository I can clone. The changes should be applied to all files, even if not opened in an editor. The file might not be opened in an editor though, but the server should receive an open request since it is a transfer of ownership.

**Comment by BoykoAlex** [comment]
@dbaeumer just checked i can confirm that docs not opened but present in doc changes are opened in editors with changes applied to them. Not sure how i missed it :-\ Maybe a VSCode upgrade helped but likely i missed this somehow. Sorry for the false alarm!-)

**Comment by dbaeumer** [comment]
Thanks for reporting back.
