### ISSUE TITLE
[meta model] supportsCustomValues is not applied to some enums that should support custom values

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode-languageserver-node#977]
I noticed in the new JSON meta model there's a `supportsCustomValues` flag on some enums. I'd like to switch to using that (instead of a hard-coded list), but it doesn't seem to match my expectations.

For example, `CompletionItemKind` does _not_ have this flag, yet in the `InitializeParams` the client provides a list of `CompletionItemKinds` is supports in its capabilities. If a server assumes it can reject any `CompletionItemKind` that don't match the list it knows about, it's possible it will reject an `InitializeParams` that has additional kinds that did not exist when that version of the server was released.

I think there are other types that fall into this category. For exampe if a client supports a new `MarkupKind` in the future and includes it in `HoverClientCapabilities.contentFormat` then a server needs to accept that value and not treat the request as invalid.

Edit: Thinking about this more, I'm actually wondering if there are _any_ enum values where a server (or client) should not be prepared for unknown values. Presumably a future version of the spec might extend _any_ enum? 🤔

**Comment by dbaeumer** [comment]
I think there is a misunderstanding about the meaning of that property. 

In LSP we have two types of enums

- one that defines the value range. There type definition is usually `type enumType = 1 | 2 | 3 | 4`. The don't support custom values since new values have to go into the spec. That still means that a server shouldn't trip over them. However clients and server are not allowed to use values that are not specified. An example is `CompletionItemKind`
- where the value range is open but we define a predefined set of values. That means clients can send value outside the range and these values might never make it into the specification. The enums are usually defined like `type enumType = string` and there will be a bunch of constants when there are predefined values. An example is `CodeActionKind`

I will close the issue. Please ping if something is still unclear.

**Comment by DanTup** [comment]
Ah, gotcha. Thanks for the clarification. It sounds like I shouldn't assume a fixed set for _any_ enums during deserialisation then, to ensure compatibility with future clients. And if I get a value I don't understand (for example if I get a `TraceValue` that didn't exist when I compiled the server), I'll just have to pick some sensible default logic.

Thanks!
