### ISSUE TITLE
didChange/didSave notification ordering

### ISSUE THREAD

**Issue by pfitzseb** [microsoft/vscode-languageserver-node#991]
In the Julia LS we have a sanity check in a `textDocument/didSave` handler that confirms the text saved to disk is what the LS expects based on applying all `textDocument/didChange` events.  This was working fine for a long time, but broke with the upgrade to LSP17.

My question is now whether there are any guarantees for notification ordering, i.e. does the client have to send all `didChange` notifications before the `didSave` notification?

**Comment by dbaeumer** [comment]
Yes, it should send all `didChange` notifications before send `didSave`. However, I had a bug only when using full text document sync which I fixed in `8.0.2-next.5`. You might want to give that a try in case you are using full document sync.

Let me know how it goes.

**Comment by pfitzseb** [comment]
Yes, we are using full document sync. Upgrading to `8.0.2-next.5` makes the issue harder to reproduce, but it isn't gone completely. It's very possible that the remaining issues are on our end though.

**Comment by dbaeumer** [comment]
One thing to note is that since everything is async it can easily be that a file on disk is already in state n + 1 but the server is still in state n for that file. This is why an open notification transfers ownership of a file to a client and a server is not allowed to fetch the content of the file from disk.

Any objection to close. We can always reopen if you think there is still an issue with the library.

**Comment by pfitzseb** [comment]
We don't check what's on disk; the comparison we make is between `didSave`'s `text` parameter and the server's document state.

I assume the remaining issues are on our end, although it's not clear to me why they've only just started happening.

Thanks for the clarification anyways!

**Comment by dbaeumer** [comment]
OK. Ping when you see something problematic.
